---
- name: Docker | Install docker packages
  tags:
    - docker
  ansible.builtin.package:
    name:
      - docker
      - docker-compose
    state: present
    update_cache: false
  become: true

- name: Docker | Start docker
  tags:
    - docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  become: true

- name: Docker | Add to the docker group the user {{ lookup('env', 'USER') }}
  tags:
    - docker
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    groups: docker
    append: true
    create_home: false
  become: true
