---
- name: Libvirt | Uninstall iptables so it can install iptables-nft later
  tags:
    - libvirt
  ansible.builtin.package:
    name: iptables
    state: absent
    update_cache: false
    force: true
  become: true

- name: Libvirt | Install KVM/QEMU packages
  tags:
    - libvirt
  ansible.builtin.package:
    name:
      - qemu-base
      - libvirt
      - virt-manager
      - spice-vdagent
      - dnsmasq
      - ebtables
    state: present
    update_cache: false
  become: true
  register: "finish_libvirt_configuration1"

- name: Libvirt | Ensure group libvirt exists
  tags:
    - libvirt
  ansible.builtin.group:
    name: libvirtd
    state: present
  become: true

- name: Libvirt | Add to the libvirt group the user {{ lookup('env', 'USER') }}
  tags:
    - libvirt
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    groups: libvirtd
    append: true
  become: true
  register: "finish_libvirt_configuration2"

- name: Libvirt | Copy file qemu.conf to /etc/libvirt
  tags:
    - libvirt
  ansible.builtin.copy:
    src: qemu.conf
    dest: /etc/libvirt
    owner: root
    group: root
    mode: '0644'
  become: true
  register: "finish_libvirt_configuration3"

- name: Libvirt | Ensure libvirt directory exists in .config
  tags:
    - libvirt
  ansible.builtin.file:
    dest: "{{ lookup('env', 'HOME') }}/.config/libvirt/"
    mode: '0770'
    group: "{{ lookup('env', 'USER') }}"
    owner: "{{ lookup('env', 'USER') }}"
    state: directory

- name: Libvirt | Copy libvirt conf to user .config directory
  tags:
    - libvirt
  ansible.builtin.copy:
    src: /etc/libvirt/libvirt.conf
    dest: "{{ lookup('env', 'HOME') }}/.config/libvirt/libvirt.conf"
    mode: '0644'
  become: true

- name: Libvirt | Change libvirt.conf to allow non root user to start a VM
  tags:
    - libvirt
  ansible.builtin.lineinfile:
    path: /etc/libvirt/libvirt.conf
    state: present
    line: 'uri_default = "qemu:///system"'
  become: true

- name: Libvirt | Restart libvirt
  tags:
    - libvirt
  ansible.builtin.service:
    name: libvirtd
    state: restarted
    enabled: true
  become: true
  when: finish_libvirt_configuration1 is changed or finish_libvirt_configuration2 is changed or finish_libvirt_configuration3 is changed

# - name: Libvirt | virsh start
#   tags:
#     - libvirt
#   ansible.builtin.command: "virsh net-autostart default && virsh net-start default"
#   become: true
#   when:  finish_libvirt_configuration1 is changed or finish_libvirt_configuration2 is changed or finish_libvirt_configuration3 is changed
