---
- name: Heavy Workstation | Include tasks from docker play
  ansible.builtin.include_tasks: tasks/docker.yml
  tags:
    - docker

- name: Heavy Workstation | Include tasks from syncthing play
  ansible.builtin.include_tasks: tasks/syncthing.yml
  tags:
    - syncthing

- name: Heavy Workstation | Include tasks from libvirt play
  ansible.builtin.include_tasks: tasks/libvirt.yml
  tags:
    - libvirt

- name: Heavy Workstation | Include tasks from windows-vm play
  ansible.builtin.include_tasks: tasks/windows-vm.yml
  tags:
    - windows-vm

- name: Heavy Workstation | Include tasks from insync play
  ansible.builtin.include_tasks: tasks/insync.yml
  tags:
    - insync

# - name: Heavy Workstation | Include tasks from samba play
#   ansible.builtin.include_tasks: tasks/samba.yml
#   tags:
#     - never
#     - samba

# - name: Heavy Workstation | Include tasks from smtpd play
#   ansible.builtin.include_tasks: tasks/smtpd.yml
#   tags:
#     - never
#     - opensmtpd

# - name: Heavy Workstation | Include tasks from portmaster play
#   ansible.builtin.include_tasks: tasks/portmaster.yml
#   tags:
#     - aur
#     - never
#     - portmaster
