---
- name: Portmaster | Install aur packages
  tags:
    - portmaster
  kewlfft.aur.aur:
    name:
      - portmaster-stub-bin
    use: yay
    state: present
    update_cache: true
  when: ansible_distribution == "Archlinux"
  ignore_errors: true

- name: Portmaster | Generate a file to start portmaster
  tags:
    - portmaster
  ansible.builtin.blockinfile:
    path: /usr/local/bin/portmaster
    create: true
    group: "{{ lookup('env', 'USER') }}"
    owner: "{{ lookup('env', 'USER') }}"
    mode: "0750"
    block: |
      #!/bin/sh
      /opt/safing/portmaster/portmaster-start app
  become: true
  when: ansible_distribution == "Archlinux"
