---
- name: Samba | Install samba packages
  tags:
    - samba
  ansible.builtin.package:
    name:
      - krb5
      - ntp
      - python-dnspython
      - openresolv
      - samba
  become: true
  when: ansible_distribution == "Archlinux"

- name: Samba | Ensure group sambausers exists
  tags:
    - samba
  ansible.builtin.group:
    name: sambausers
    state: present
  become: true

- name: Samba | Ensure /samba directory exists
  tags:
    - samba
  ansible.builtin.file:
    dest: /samba
    group: sambausers
    mode: "1770"
    state: directory
  become: true

- name: Samba | Copy file smb.conf to /etc/samba/
  tags:
    - samba
  ansible.builtin.copy:
    src: smb.conf
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: finish samba configuration

- name: Samba | File to Allow samba in ufw
  tags:
    - samba
  ansible.builtin.copy:
    src: samba-ufw
    dest: /etc/ufw/applications.d/samba
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Samba | Allow samba in ufw
  tags:
    - samba
  community.general.ufw:
    rule: allow
    name: Samba
  become: true

- name: Samba | Create samba password and the user {{ lookup('env', 'USER') }}
  tags:
    - samba
  ansible.builtin.shell: set -o pipefail && echo '{{ samba_pass }}'; echo '{{ samba_pass }}') | smbpasswd -s -a {{ lookup('env', 'USER') }}
  register: smbpasswd
  changed_when: "'Added user' in smbpasswd.stdout"
  become: true
  listen: finish samba configuration

- name: Samba | Start samba (smb) service
  tags:
    - samba
  ansible.builtin.service:
    name: smb
    state: restarted
    enabled: true
  become: true
  listen: finish samba configuration

- name: Samba | Start samba (nmb) service
  tags:
    - samba
  ansible.builtin.service:
    name: nmb
    state: restarted
    enabled: true
  become: true
  listen: finish samba configuration
