# tasks to complete before running roles
- hosts: all
  tags: always
  become: true
  pre_tasks:
    - name: Pre-run | update package cache (arch)
      tags: always
      community.general.pacman: update_cache=yes
      changed_when: false
      when: ansible_distribution == "Archlinux"

    - name: Pre-run | update package cache (debian, etc)
      tags: always
      ansible.builtin.apt: update_cache=yes
      changed_when: false
      when: ansible_distribution in ["Debian", "Ubuntu"]
  vars_prompt:
    - name: neomutt_email
      prompt: "What is the email you want in neomutt?"
      private: no
    - name: neomutt_password
      prompt: "What is the password of your email in neomutt?"

# run roles
- hosts: all
  tags:
    - base
    - light-workstation
    - heavy-workstation
    - samsung-expert
    - work
    - server
  become: true
  roles:
    - base

- hosts: light-workstation
  tags:
    - light-workstation
    - heavy-workstation
    - samsung-expert
  roles:
    - light-workstation

- hosts: heavy-workstation
  tags:
    - heavy-workstation
    - samsung-expert
  roles:
    - heavy-workstation

- hosts: work
  tags:
    - work
    - samsung-expert
  roles:
    - work

- hosts: samsung-expert
  tags: samsung-expert
  roles:
    - samsung-expert

- hosts: server
  tags: server
  become: true
  roles:
    - server

# end of run cleanup
- hosts: all
  become: true
  tasks:
  - name: Post-run | Cleanup package cache (debian and ubuntu)
    tags: always
    ansible.builtin.apt:
      autoclean: yes
    changed_when: false
    when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]

  - name: Post-run | Autoremove orphan packages (debian and ubuntu)
    tags: always
    ansible.builtin.apt:
      autoremove: yes
      purge: yes
    when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
