- hosts: localhost
  tags:
    - workstation
  connection: local
  # vars_prompt:
  #   - name: "user"
  #     prompt: "Enter your system username"
  #     private: false
  #   - name: "fullname"
  #     prompt: "Enter your full real name"
  #     private: false
  #   - name: "personal_email"
  #     prompt: "Enter your personal email address"
  #     private: false
  #   - name: "work_email"
  #     prompt: "Enter your work email address"
  #     private: false
  pre_tasks:
    - name: Update cache of package manager
      tags:
        - full-install
        - light-install
        - packages
        - always
      package:
        update_cache: true
      become: true

  tasks:
    - include_tasks: tasks/ssh.yml
      tags:
        - full-install
        - light-install
        - ssh
    - include_tasks: tasks/collections-install.yml
    - include_tasks: tasks/ansible.yml
    - include_tasks: tasks/audio.yml
    - include_tasks: tasks/keyboard-layout.yml
    - include_tasks: tasks/locale.yml
    - include_tasks: tasks/cron.yml
      tags:
        - full-install
        - light-install
        - cron
    - include_tasks: tasks/git.yml
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/linux-scripts.yml
    - include_tasks: tasks/bluetooth.yml
    - include_tasks: tasks/fish.yml
    - include_tasks: tasks/libvirt.yml
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/dwm.yml
    - include_tasks: tasks/st.yml
    - include_tasks: tasks/dmenu.yml
    - include_tasks: tasks/dwmstatus.yml
    - include_tasks: tasks/aur-packages.yml
    - include_tasks: tasks/dwmblocks.yml
    - include_tasks: tasks/slock.yml
    - include_tasks: tasks/neovim.yml
    - include_tasks: tasks/lfub.yml
    - include_tasks: tasks/preload.yml
    - include_tasks: tasks/brave.yml
    - include_tasks: tasks/authy.yml
    - include_tasks: tasks/timeshift.yml
    - include_tasks: tasks/docker.yml
    - include_tasks: tasks/network.yml
    - include_tasks: tasks/eureciclo.yml
    - include_tasks: tasks/aur-packages2.yml
    - include_tasks: tasks/doas.yml
