---
- name: Install docker packages
  tags:
    - docker
  ansible.builtin.package:
    name:
      - docker
      - docker-compose
    state: present
    update_cache: false
  become: true

- name: Start docker
  tags:
    - docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  become: true

- name: Add the user {{ lookup('env', 'USER') }} to the docker group
  tags:
    - docker
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    groups: docker
    append: true
    create_home: false
  become: true
