---
- name: Ensure anki directory exists.
  tags:
    - full-install
    - light-install
    - anki
  ansible.builtin.file:
    dest: "{{ ansible_env.HOME }}/.config/anki/install-files"
    mode: 0700
    state: directory

- name: Get latest anki release
  tags:
    - full-install
    - light-install
    - anki
  ansible.builtin.uri:
    url: https://api.github.com/repos/ankitects/anki/releases/latest
    return_content: true
  register: json_reponse

- name: Download anki installer
  tags:
    - full-install
    - light-install
    - anki
  ansible.builtin.get_url:
    url: "{{ json_reponse.json.assets.browser_download_url }}"
    dest: "{{ ansible_env.HOME }}/.config/anki/anki-installer.tar.zst"
    force: true
  notify: "proceed anki installation"
