---
- name: create ansible user
  tags:
    - full-install
    - light-install
    - users
    - ansible
  ansible.builtin.user:
    name: ansible
    system: true
  become: true

- name: copy sudoers_ansible
  tags:
    - full-install
    - users
    - ansible
    - light-install
  ansible.builtin.copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'sudoers_ansible', dest: '/etc/sudoers.d/ansible' }
    - { src: 'sudoers_frank', dest: '/etc/sudoers.d/frank' }
  become: true

- name: Clone ansible repository
  tags:
    - full-install
    - light-install
    - ansible
  ansible.builtin.git:
    version: main
    repo: git@github.com:andre-gonzalez/ansible.git
    dest: "{{ lookup('env', 'HOME') }}/.config/ansible"
    accept_hostkey: true
