- name: create ansible user
  tags:
    - full-install
    - users
    - light-install
  user:
    name: ansible
    system: yes
  become: true

- name: copy sudoers_ansible
  tags:
    - full-install
    - users
    - light-install
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'sudoers_ansible', dest: '/etc/sudoers.d/ansible' }
    - { src: 'sudoers_frank', dest: '/etc/sudoers.d/frank' }
  become: true

- name: Clone ansible repository
  tags:
    - full-install
    - light-install
    - ansible
  ansible.builtin.git:
    repo: git@github.com:andre-gonzalez/my-dwm.git
    dest: "{{ lookup('env', 'HOME') }}/.config/ansible"
    accept_hostkey: yes
