- name: Install audio packages
  tags:
    - full-install
    - audio
    - light-install
  package:
    name:
      - pulseaudio
      - alsa-utils
      - pavucontrol
    state: present
  become: true
