---
- name: Set bluez_utils and pulseaudio_bluetooth variable when distribution is Archlinux (if necessary)
  tags:
    - full-install
    - light-install
    - bluetooth
  ansible.builtin.set_fact:
    bluez_utils: bluez-utils
    pulseaudio_bluetooth: pulseaudio-bluetooth
  when: ansible_distribution == "Archlinux"

- name: Set bluez_utils and pulseaudio_bluetooth variable when distribution is Ubuntu (if necessary)
  tags:
    - full-install
    - light-install
    - bluetooth
  ansible.builtin.set_fact:
    bluez_utils: bluez-alsa-utils
    pulseaudio_bluetooth: pulseaudio-module-bluetooth
  when: ansible_distribution == "Ubuntu"

- name: Install bluetooth packages
  tags:
    - full-install
    - light-install
    - bluetooth
  ansible.builtin.package:
    name:
      - bluez
      - bluez-tools
      - "{{ bluez_utils }}"
      - "{{ pulseaudio_bluetooth }}"
    state: present
    update_cache: false
  become: true

- name: start bluetooth
  tags:
    - full-install
    - light-install
    - bluetooth
  ansible.builtin.service:
    name: bluetooth
    state: started
    enabled: yes
  become: yes
