- name: required libraries for brave
  tags:
    - brave
    - full-install
    - light-install
  package:
    name: ["curl", "apt-transport-https"]
  become: true
  when: ansible_distribution == "Ubuntu"

- name: Brave Browser archive-keyring.gpg download
  tags:
    - brave
    - full-install
    - light-install
  get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
  become: true
  when: ansible_distribution == "Ubuntu"

- name: Brave Browser PPA setting
  tags:
    - brave
    - full-install
    - light-install
  shell: echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | tee /etc/apt/sources.list.d/brave-browser-release.list
  become: true
  when: ansible_distribution == "Ubuntu"

- name: Brave Browser apt installation
  tags:
    - brave
    - full-install
    - light-install
  package:
    name: brave-browser
    update_cache: yes
  become: true
  when: ansible_distribution == "Ubuntu"

- name: Install brave via aur package
  tags:
    - aur
    - never
    - brave
  kewlfft.aur.aur:
    name:
      - brave-bin
    use: yay
    state: present
    update_cache: yes
  when: ansible_distribution == "Archlinux"
