- name: Install collection kewlfft.aur
  tags:
    - aur
    - never
  community.general.ansible_galaxy_install:
    type: collection
    name: kewlfft.aur
  when: ansible_distribution == "Archlinux"
