- name: start cron
  tags:
    - start-services
    - full-install
  ansible.builtin.service:
    name: cronie
    state: started
    enabled: yes
  become: yes

- name: install cron job (ansible-pull)
  tags:
    - full-install
    - crontab
  cron:
    user: ansible
    name: "ansible provision"
    minute: "*/10"
    job: "/usr/bin/ansible-pull -o -U https://github.com/andre-gonzalez/ansible-pull.git > /dev/null"
  become: yes

- name: install cron job (profile-selector)
  tags:
    - full-install
    - crontab
  cron:
    user: "{{ lookup('env', 'USER') }}"
    name: "profile-selector"
    special_time: reboot
    job: "sleep 15 && DISPLAY=:0 /usr/local/bin/profile-selector"
  become: yes

- name: install cron job (remove downloads folder)
  tags:
    - full-install
    - crontab
  cron:
    user: "{{ lookup('env', 'USER') }}"
    name: "remove-downloads-folder-reboot"
    special_time: reboot
    job: "sleep 60 && rm -r {{ lookup('env', 'HOME') }}/Downloads"

- name: install cron job (remove downloads folder)
  tags:
    - full-install
    - crontab
  cron:
    user: "{{ lookup('env', 'USER') }}"
    name: "remove-downloads-folder"
    minute: "*/10"
    job: "sleep 60 && rm -r {{ lookup('env', 'HOME') }}/Downloads"
