- name: Set cron variable when distribution is Archlinux
  set_fact:
    cron: cronie
  when: ansible_distribution == "Archlinux"

- name: Set cron variable when distribution is Ubuntu
  set_fact:
    cron: cron
  when: ansible_distribution == "Ubuntu"

- name: Install cron
  tags:
    - full-install
    - light-install
  package:
    name: " {{ cron }}"
    state: present
    update_cache: true
  become: true

- name: start cron
  tags:
    - full-install
    - light-install
  ansible.builtin.service:
    name: "{{cron}}"
    state: started
    enabled: yes
  become: yes

- name: install cron job (ansible-pull)
  tags:
    - full-install
    - crontab
  cron:
    user: ansible
    name: "ansible provision"
    minute: "*/10"
    job: "/usr/bin/ansible-pull --vault-password-file {{ lookup('env', 'HOME') }}/.vault_key -o -U https://github.com/andre-gonzalez/ansible-pull.git > /dev/null"
  become: yes

- name: install cron job (profile-selector)
  tags:
    - full-install
    - crontab
    - light-install
  cron:
    user: "{{ lookup('env', 'USER') }}"
    name: "profile-selector"
    special_time: reboot
    job: "sleep 15 && DISPLAY=:0 /usr/local/bin/profile-selector"
  become: yes

- name: install cron job (remove downloads folder)
  tags:
    - full-install
    - crontab
    - light-install
  cron:
    user: "{{ lookup('env', 'USER') }}"
    name: "remove-downloads-folder-reboot"
    special_time: reboot
    job: "sleep 60 && rm -r {{ lookup('env', 'HOME') }}/Downloads"

- name: install cron job (remove downloads folder)
  tags:
    - full-install
    - crontab
  cron:
    user: "{{ lookup('env', 'USER') }}"
    name: "remove-downloads-folder"
    minute: "*/10"
    job: "sleep 60 && rm -r {{ lookup('env', 'HOME') }}/Downloads"

- name: install cron job (battery notification)
  tags:
    - full-install
    - crontab
    - light-install
  cron:
    user: "{{ lookup('env', 'USER') }}"
    name: "battery notification"
    minute: "*/10"
    job: "/bin/sh {{ lookup('env', 'HOME') }}/.local/bin/battery-warning.sh"
