---
- name: Install DBeaver package
  tags:
    - full-install
    - light-install
    - packages
    - dbeaver
  ansible.builtin.package:
    name: dbeaver # missing ubuntu
    state: present
    update_cache: false
  become: true

- name: Copy DBeaver configuration files
  tags:
    - full-install
    - light-install
    - dbeaver
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ansible_env.USER }}"
    mode: 0644
  loop:
    - { src: "data-sources.json", dest: "{{ ansible_env.HOME }}/.local/share/DBeaverData/workspace6/General/.dbeaver" }
    - { src: ".data-sources.json.bak", dest: "{{ ansible_env.HOME }}/.local/share/DBeaverData/workspace6/General/.dbeaver" }
    - { src: "project-metadata.json", dest: "{{ ansible_env.HOME }}/.local/share/DBeaverData/workspace6/General/.dbeaver" }
