---
- name: Clone dmenu
  tags:
    - full-install
    - light-install
    - dmenu
  ansible.builtin.git:
    version: master
    repo: https://git.suckless.org/dmenu
    dest: "{{ lookup('env', 'HOME') }}/.config/dmenu"
  ignore_errors: true

- name: Install dmenu
  tags:
    - full-install
    - light-install
    - dmenu
  community.general.make:
    chdir: "{{ lookup('env', 'HOME') }}/.config/dmenu"
    target: install
  become: true
