- name: Install doas package
  tags:
    - full-install
    - doas
    - light-install
  package:
    name: doas
    state: present
    update_cache: false
  become: true

- name: copy file doas.conf to /etc
  tags:
    - full-install
    - doas
    - light-install
  copy:
    src: doas.conf
    dest: /etc
    owner: root
    group: root
    mode: 0644
  become: yes

- name: uninstall sudo
  tags:
    - packages-remove
    - packages
    - light-install
    - doas
    - full-install
  package:
    name:
      - sudo
    state: absent
    update_cache: no
  become: true
