---
- name: Cloning .dotfiles
  tags:
    - full-install
    - light-install
    - dotfiles
  ansible.builtin.git:
    version: main
    repo: git@github.com:andre-gonzalez/dotfiles.git
    dest: "{{ ansible_env.HOME }}/.dotfiles"
    recursive: true
    update: true
    bare: true
    accept_hostkey: true

- name: set up dotfiles
  tags:
    - full-install
    - light-install
    - dotfiles
  ansible.builtin.command: "/usr/bin/git --git-dir={{ ansible_env.HOME }}/.dotfiles/ --work-tree={{ ansible_env.HOME }} checkout -f"
