- name: Cloning .dotfiles
  tags:
    - dotfiles
    - full-install
  ansible.builtin.git:
    repo: 'https://github.com/andre-gonzalez/dotfiles'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    bare: yes
    version: main

- name: set up dotfiles
  ansible.builtin.command: "/usr/bin/git --git-dir={{ lookup('env', 'HOME') }}/.dotfiles/ --work-tree={{ lookup('env', 'HOME') }} checkout -f"
