- name: Cloning .dotfiles
  tags:
    - dotfiles
    - full-install
  ansible.builtin.git:
    repo: 'https://github.com/andre-gonzalez/dotfiles'
    dest: "/home/frank/.dotfiles"
    recursive: yes
    update: yes
    bare: yes
    version: main
