- name: Cloning .dotfiles
  tags:
    - dotfiles
    - full-install
  ansible.builtin.git:
    repo: 'https://github.com/andre-gonzalez/dotfiles'
    dest: "/home/{{ user }}/.dotfiles"
    recursive: yes
    update: yes
    bare: yes
    version: main

- name: set up dotfiles
  ansible.builtin.command: /usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME checkout -f
