- name: Clone dwmblocks
  tags:
    - dwmblocks-install
    - full-install
  git:
    repo: https://github.com/Andre-gonzalez/my-dwmblocks
    dest: "{{ lookup('env', 'USR') | default('nobody', True) }}/.config/dwmblocks"

- name: Install dwmblocks
  tags:
    - dwmblocks-install
    - full-install
  make:
    chdir: "{{ lookup('env', 'USR') | default('nobody', True) }}/.config/dwmblocks"
    target: install
  become: yes
