- name: Install packages necessary for dwmblocks
  tags:
    - full-install
    - light-install
    - dwmblocks
  kewlfft.aur.aur:
    name:
      - checkupdates+aur
    use: yay
    state: present
    update_cache: yes
  when: ansible_distribution == "Archlinux"

- name: Clone dwmblocks
  tags:
    - full-install
    - light-install
    - dwmblocks
  ansible.builtin.git:
    repo: git@github.com:andre-gonzalez/my-dwmblocks.git
    dest: "{{ lookup('env', 'HOME') }}/.config/dwmblocks"
    accept_hostkey: yes

- name: Install dwmblocks
  tags:
    - full-install
    - light-install
    - dwmblocks
  make:
    chdir: "{{ lookup('env', 'HOME') }}/.config/dwmblocks"
    target: install
  become: yes

- name: Create symbolic links for the dwmblocks scripts
  tags:
    - full-install
    - light-install
    - dwmblocks
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    state: link
  loop:
    - { src: "{{ lookup('env', 'HOME') }}/.config/dwmblocks/bar-functions/dwm_packages", dest: "{{ lookup('env', 'HOME') }}/.scripts/dwm_packages" }
    - { src: "{{ lookup('env', 'HOME') }}/.config/dwmblocks/bar-functions/dwm_spotify", dest: "{{ lookup('env', 'HOME') }}/.scripts/dwm_spotify" }
    - { src: "{{ lookup('env', 'HOME') }}/.config/dwmblocks/bar-functions/dwm_connman", dest: "{{ lookup('env', 'HOME') }}/.scripts/dwm_connman" }
    - { src: "{{ lookup('env', 'HOME') }}/.config/dwmblocks/bar-functions/dwm_resources", dest: "{{ lookup('env', 'HOME') }}/.scripts/dwm_resources" }
    - { src: "{{ lookup('env', 'HOME') }}/.config/dwmblocks/bar-functions/dwm_battery", dest: "{{ lookup('env', 'HOME') }}/.scripts/dwm_battery" }
    - { src: "{{ lookup('env', 'HOME') }}/.config/dwmblocks/bar-functions/dwm_backlight", dest: "{{ lookup('env', 'HOME') }}/.scripts/dwm_backlight" }
    - { src: "{{ lookup('env', 'HOME') }}/.config/dwmblocks/bar-functions/dwm_pulse", dest: "{{ lookup('env', 'HOME') }}/.scripts/dwm_pulse" }
    - { src: "{{ lookup('env', 'HOME') }}/.config/dwmblocks/bar-functions/dwm_bluetooth", dest: "{{ lookup('env', 'HOME') }}/.scripts/dwm_bluetooth" }
    - { src: "{{ lookup('env', 'HOME') }}/.config/dwmblocks/bar-functions/dwm_date", dest: "{{ lookup('env', 'HOME') }}/.scripts/dwm_date" }
  become: true
