---
#- name: Install packages necessary for dwmblocks
#  tags:
#    - never
#    - aur
#  kewlfft.aur.aur:
#    name:
#     - checkupdates+aur
#    use: yay
#    state: present
#    update_cache: true
#  when: ansible_distribution == "Archlinux"
#  ignore_errors: true

- name: Clone dwmblocks
  tags:
    - full-install
    - light-install
    - dwmblocks
  ansible.builtin.git:
    version: main
    repo: git@github.com:andre-gonzalez/dwmblocks.git
    dest: "{{ ansible_env.HOME }}/.config/dwmblocks"
    accept_hostkey: true
  ignore_errors: true

- name: Install dwmblocks
  tags:
    - full-install
    - light-install
    - dwmblocks
  community.general.make:
    chdir: "{{ ansible_env.HOME }}/.config/dwmblocks"
    target: install
  become: true

- name: Create symbolic links for the dwmblocks scripts
  tags:
    - full-install
    - light-install
    - dwmblocks
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    state: link
  loop:
    - { src: "{{ ansible_env.HOME }}/.config/dwmblocks/bar-functions/dwm_packages", dest: "{{ ansible_env.HOME }}/.scripts/dwm_packages" }
    - { src: "{{ ansible_env.HOME }}/.config/dwmblocks/bar-functions/dwm_spotify", dest: "{{ ansible_env.HOME }}/.scripts/dwm_spotify" }
    - { src: "{{ ansible_env.HOME }}/.config/dwmblocks/bar-functions/dwm_systemd_networkd.sh", dest: "{{ ansible_env.HOME }}/.scripts/dwm_systemd_networkd" }
    - { src: "{{ ansible_env.HOME }}/.config/dwmblocks/bar-functions/dwm_resources", dest: "{{ ansible_env.HOME }}/.scripts/dwm_resources" }
    - { src: "{{ ansible_env.HOME }}/.config/dwmblocks/bar-functions/dwm_battery", dest: "{{ ansible_env.HOME }}/.scripts/dwm_battery" }
    - { src: "{{ ansible_env.HOME }}/.config/dwmblocks/bar-functions/dwm_backlight", dest: "{{ ansible_env.HOME }}/.scripts/dwm_backlight" }
    - { src: "{{ ansible_env.HOME }}/.config/dwmblocks/bar-functions/dwm_pulse", dest: "{{ ansible_env.HOME }}/.scripts/dwm_pulse" }
    - { src: "{{ ansible_env.HOME }}/.config/dwmblocks/bar-functions/dwm_bluetooth", dest: "{{ ansible_env.HOME }}/.scripts/dwm_bluetooth" }
    - { src: "{{ ansible_env.HOME }}/.config/dwmblocks/bar-functions/dwm_date", dest: "{{ ansible_env.HOME }}/.scripts/dwm_date" }
    - { src: "{{ ansible_env.HOME }}/.config/dwmblocks/bar-functions/dwm_weather", dest: "{{ ansible_env.HOME }}/.scripts/dwm_weather" }
    - { src: "{{ ansible_env.HOME }}/.config/dwmblocks/bar-functions/dwm_countdown", dest: "{{ ansible_env.HOME }}/.scripts/dwm_countdown" }
    - { src: "{{ ansible_env.HOME }}/.config/dwmblocks/bar-functions/dwm_date_brasil", dest: "{{ ansible_env.HOME }}/.scripts/dwm_date_brasil" }
  become: true
