- name: Clone dwmstatus
  tags:
    - full-install
    - light-install
    - dwmblocks
  ansible.builtin.git:
    repo: https://git.suckless.org/dwmstatus
    dest: "{{ lookup('env', 'HOME') }}/.config/dwmstatus"

- name: Install dwmstatus
  tags:
    - full-install
    - light-install
    - dwmblocks
  make:
    chdir: "{{ lookup('env', 'HOME') }}/.config/dwmstatus"
    target: install
  become: yes
