- name: Clone dwmstatus
  tags:
    - dwmblocks-install
    - full-install
  git:
    repo: https://git.suckless.org/dwmstatus
    dest: "{{ lookup('env', 'USR') | default('nobody', True) }}/.config/dwmstatus"

- name: Install dwmstatus
  tags:
    - dwmblocks-install
    - full-install
  make:
    chdir: "{{ lookup('env', 'USR') | default('nobody', True) }}/.config/dwmstatus"
    target: install
  become: yes
