---
- name: Ensure eureciclo directory exists
  tags:
    - full-install
    - light-install
    - eureciclo
  ansible.builtin.file:
    dest: "{{ lookup('env', 'HOME') }}/eureciclo"
    mode: 0770
    state: directory

- name: Clone utils repository
  tags:
    - full-install
    - light-install
    - eureciclo
  ansible.builtin.git:
    repo: git@bitbucket.org:redeciclo/utils.git
    dest: "{{ lookup('env', 'HOME') }}/eureciclo/utils/main-utils"
    accept_hostkey: true
  ignore_errors: true

- name: Clone queries repository
  tags:
    - full-install
    - light-install
    - eureciclo
  ansible.builtin.git:
    repo: git@bitbucket.org:redeciclo/queries.git
    dest: "{{ lookup('env', 'HOME') }}/eureciclo/queries/main-queries"
    accept_hostkey: true
  ignore_errors: true

- name: Clone salesops-dw repository
  tags:
    - full-install
    - light-install
    - eureciclo
  ansible.builtin.git:
    repo: git@bitbucket.org:redeciclo/salesops-dw.git
    dest: "{{ lookup('env', 'HOME') }}/eureciclo/salesops-dw/main-salesops-dw"
    accept_hostkey: true
  ignore_errors: true

- name: Clone diversos repository
  tags:
    - full-install
    - light-install
    - eureciclo
  ansible.builtin.git:
    repo: git@bitbucket.org:andre-gonzalez/diversos.git
    dest: "{{ lookup('env', 'HOME') }}/eureciclo/diversos/main-diversos"
    accept_hostkey: true
  ignore_errors: true

- name: Clone conectar-bancos repository
  tags:
    - full-install
    - light-install
    - eureciclo
  ansible.builtin.git:
    repo: git@bitbucket.org:andre-gonzalez/conectar-bancos.git
    dest: "{{ lookup('env', 'HOME') }}/eureciclo/conectar-bancos"
    accept_hostkey: true
  ignore_errors: true

- name: Ensure eureciclo downloads directory exists.
  tags:
    - full-install
    - light-install
    - eureciclo
  ansible.builtin.file:
    dest: "{{ lookup('env', 'HOME') }}/eureciclo/downloads/query"
    mode: 0770
    state: directory
