---
- name: Ensure eureciclo directory exists
  tags:
    - full-install
    - light-install
    - eureciclo
  ansible.builtin.file:
    dest: "{{ ansible_env.HOME }}/eureciclo"
    mode: 0770
    state: directory

- name: Clone utils repository
  tags:
    - full-install
    - light-install
    - eureciclo
  ansible.builtin.git:
    version: main
    repo: git@bitbucket.org:redeciclo/utils.git
    dest: "{{ ansible_env.HOME }}/eureciclo/utils/main-utils"
    accept_hostkey: true
  ignore_errors: true

- name: Clone queries repository
  tags:
    - full-install
    - light-install
    - eureciclo
  ansible.builtin.git:
    version: main
    repo: git@bitbucket.org:redeciclo/queries.git
    dest: "{{ ansible_env.HOME }}/eureciclo/queries/main-queries"
    accept_hostkey: true
  ignore_errors: true

- name: Clone salesops-dw repository
  tags:
    - full-install
    - light-install
    - eureciclo
  ansible.builtin.git:
    version: main
    repo: git@bitbucket.org:redeciclo/salesops-dw.git
    dest: "{{ ansible_env.HOME }}/eureciclo/salesops-dw/main-salesops-dw"
    accept_hostkey: true
  ignore_errors: true

- name: Clone diversos repository
  tags:
    - full-install
    - light-install
    - eureciclo
  ansible.builtin.git:
    version: main
    repo: git@bitbucket.org:andre-gonzalez/diversos.git
    dest: "{{ ansible_env.HOME }}/eureciclo/diversos/main-diversos"
    accept_hostkey: true
  ignore_errors: true

- name: Clone conectar-bancos repository
  tags:
    - full-install
    - light-install
    - eureciclo
  ansible.builtin.git:
    version: main
    repo: git@bitbucket.org:andre-gonzalez/conectar-bancos.git
    dest: "{{ ansible_env.HOME }}/eureciclo/conectar-bancos"
    accept_hostkey: true
  ignore_errors: true

- name: Ensure eureciclo downloads directory exists.
  tags:
    - full-install
    - light-install
    - eureciclo
  ansible.builtin.file:
    dest: "{{ ansible_env.HOME }}/eureciclo/downloads/query"
    mode: 0770
    state: directory

- name: Create symbolic links for scripts
  tags:
    - full-install
    - light-install
    - eureciclo
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    state: link
  loop:
    - { src: "{{ ansible_env.HOME }}/eureciclo/datalake-infra/main-datalake-infra/public-ip-ec2-instance.sh", dest: "{{ ansible_env.HOME }}/.scripts/public-ip-ec2-instance" }
    - { src: "{{ ansible_env.HOME }}/eureciclo/datalake-infra/main-datalake-infra/start-ec2-instance.sh", dest: "{{ ansible_env.HOME }}/.scripts/start-ec2-instance" }
    - { src: "{{ ansible_env.HOME }}/eureciclo/datalake-infra/main-datalake-infra/stop-ec2-instance.sh", dest: "{{ ansible_env.HOME }}/.scripts/stop-ec2-instance" }
  become: true
