- name: Git personal setup email
  tags:
    - git-personal
    - full-install
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ personal_email }}"

- name: Git personal setup name
  tags:
    - git-personal
    - full-install
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ fullname }}"

- name: Git eureciclo email
  tags:
    - git-eureciclo
    - full-install
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ work_email }}"
