- name: Git personal setup email
  tags:
    - git-personal
    - full-install
  community.general.git_config:
    name: user.email
    scope: global
    value: "lopescg@gmail.com"

- name: Git personal setup name
  tags:
    - git-personal
    - full-install
  community.general.git_config:
    name: user.name
    scope: global
    value: "André Gonzalez"

- name: Git eureciclo email
  tags:
    - git-eureciclo
    - full-install
  community.general.git_config:
    name: user.email
    scope: global
    value: "andre.gonzalez@nhecotech.com"
