- name: Install git
  tags:
    - git
    - full-install
    - light-install
  package:
    name: git
    state: present
    update_cache: false
  become: true

- name: Git personal setup email
  tags:
    - git-personal
    - full-install
    - light-install
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ personal_email }}"

- name: Git personal setup name
  tags:
    - git-personal
    - full-install
    - light-install
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ fullname }}"
