- name: Install lf packages
  tags:
    - full-install
    - light-install
    - lf
  kewlfft.aur.aur:
    name:
      - lf
      - python-ueberzug-git
      - ttf-symbola
    use: yay
    state: present
    update_cache: yes
  when: ansible_distribution == "Archlinux"
  ignore_errors: yes

- name: Install lf packages
  tags:
    - full-install
    - light-install
    - lf
  shell: env CGO_ENABLED=0 go install -ldflags="-s -w" github.com/gokcehan/lf@latest
  become: true
  when: ansible_distribution == "Ubuntu"

- name: copy lfub to /usr/local/bin
  tags:
    - full-install
    - light-install
    - lf
  copy:
    src: lfub
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755
  become: yes
