- name: Install aur packages
  tags:
    - full-install
    - light-install
    - lf
  kewlfft.aur.aur:
    name:
      - lf
      - python-ueberzug-git
      - ttf-symbola
    use: yay
    state: present
    update_cache: yes
  when: ansible_distribution == "Archlinux"

- name: copy lfub to /usr/local/bin
  tags:
    - full-install
    - light-install
    - lf
  copy:
    src: lfub
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755
  become: yes
