- name: Install aur packages
  tags:
    - aur-packages-install
    - packages-install
    - packages
    - full-install
  kewlfft.aur.aur:
    name:
      - lf
    use: yay
    state: present
    update_cache: yes
  when: ansible_distribution == "Archlinux"

- name: copy lfub to /usr/local/bin
  tags:
    - full-install
    - lf
    - light-install
  copy:
    src: lfub
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755
  become: yes
