- name: Install KVM/QEMU packages
  tags:
    - full-install
    - light-install
    - libvirt
  package:
    name:
      - qemu-base
      - qemu-desktop
      - libvirt
      - virt-manager
      - spice-vdagent
    state: present
    update_cache: false
  become: true

- name: Ensure group libvirtd exists
  tags:
    - full-install
    - light-install
    - libvirt
  ansible.builtin.group:
    name: libvirtd
    state: present
  become: yes

- name: add the user "{{ lookup('env', 'USER') }}" to the libvirt group
  tags:
    - full-install
    - light-install
    - libvirt
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    group: libvirtd
  become: yes

- name: copy file qemu.conf to /etc/libvirt
  tags:
    - full-install
    - light-install
    - libvirt
  copy:
    src: qemu.conf
    dest: /etc/libvirt
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: restart libvirt

handlers:
  - name: restart libvirt
    tags:
      - full-install
      - light-install
      - libvirt
    ansible.builtin.service:
      name: libvirtd
      state: restarted
      enabled: yes
    become: yes
