---
- name: Install KVM/QEMU packages
  tags:
    - full-install
    - light-install
    - libvirt
  ansible.builtin.package:
    name:
      - qemu-base
      - qemu-desktop
      - libvirt
      - virt-manager
      - spice-vdagent
    state: present
    update_cache: false
  become: true
  notify: restart libvirt

- name: Ensure group libvirt exists
  tags:
    - full-install
    - light-install
    - libvirt
  ansible.builtin.group:
    name: libvirt
    state: present
  become: true

- name: add the user {{ lookup('env', 'USER') }} to the libvirt group
  tags:
    - full-install
    - light-install
    - libvirt
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    group: libvirt
  become: true

- name: copy file qemu.conf to /etc/libvirt
  tags:
    - full-install
    - light-install
    - libvirt
  ansible.builtin.copy:
    src: qemu.conf
    dest: /etc/libvirt
    owner: root
    group: root
    mode: 0644
  become: true
  notify: restart libvirt
