- name: Install KVM/QEMU packages
  tags:
    - libvirt
    - full-install
  package:
    name:
      - qemu
      - libvirt
      - virt-manager
      - spice-vdagent
    state: present
    update_cache: false
  become: true

- name: Ensure group libvirtd exists
  ansible.builtin.group:
    name: libvirtd
    state: present
  become: yes

- name: add the frank user to the libvirt group
  tags:
    - libvirt
    - full-install
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    group: libvirtd
  become: yes

- name: copy file qemu.conf to /etc/libvirt
  tags:
    - libvirt
    - full-install
  copy:
    src: qemu.conf
    dest: /etc/libvirt
    owner: root
    group: root
    mode: 0644
  become: yes

- name: start libvirt
  tags:
    - start-services
    - full-install
  ansible.builtin.service:
    name: libvirtd
    state: started
    enabled: yes
  become: yes
