- name: Set timezone to "{{ timezone }}"
  tags:
    - timezone
    - full-install
  timezone: "{{ timezone }}"

- name: Ensure the locale exists
  tags:
    - locale
    - full-install
  community.general.locale_gen:
    name: "{{ locale }}"
    state: present

- name: set keyboard layout
  ansible.builtin.command: setxkbmap -layout "{{ keyboard-layout }}" -variant "{{ keyboard-variant }}" && setxkbmap -option caps:escape
