- name: Set timezone to "{{ timezone }}"
  tags:
    - timezone
    - full-install
  community.general.timezone:
    name: "{{ timezone }}"
  become: true

- name: Ensure the locale exists
  tags:
    - locale
    - full-install
  community.general.locale_gen:
    name: "{{ locale }}"
    state: present
  become: true
