- name: Set timezone to {{ timezone }}
  tags:
    - timezone
    - full-install
  timezone: name={{ timezone }}

- name: Ensure the locale {{ locale }} exists
  tags:
    - locale
    - full-install
  locale_gen:  name={{ locale }} state=present

- name: set keyboard layout
  ansible.builtin.command: setxkbmap -layout us -variant dvorak-intl && setxkbmap -option caps:escape
