---
- name: Install neovim
  tags:
    - full-install
    - light-install
    - neovim
  ansible.builtin.package:
    name:
      - neovim
    state: present
    update_cache: false
  become: true
  notify:
    - Install treesitter
    - Install nvim plugins

- name: Install language servers packages
  tags:
    - full-install
    - light-install
    - neovim
  ansible.builtin.package:
    name:
      - pyright # python language server
      - bash-language-server # bash language server
    state: present
    update_cache: false
  become: true
  when: ansible_distribution == "Archlinux"

- name: Install pyright (python language server via snap)
  tags:
    - full-install
    - light-install
    - neovim
  community.general.snap:
    name:
      - pyright
    state: present
    classic: true
  become: true
  when: ansible_distribution == "Ubuntu"

- name: Install sql-language-server and ansible-language-server package
  tags:
    - aur
    - never
  kewlfft.aur.aur:
    name:
      - sqls-bin
      - ansible-language-server
      - terraform-ls
    use: yay
    state: present
    update_cache: true
  when: ansible_distribution == "Archlinux"
  ignore_errors: true

- name: Install grammarly-languageserver and json language server
  tags:
    - full-install
    - light-install
    - neovim
  community.general.npm:
    name:
      - grammarly-languageserver
      - vscode-langservers-extracted
    global: true
    state: present
  become: true

- name: Install ansible-language-server when distribution in Ubuntu or Debian
  tags:
    - full-install
    - light-install
    - neovim
  community.general.npm:
    name: ansible-language-server
    global: true
    state: present
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Create neovim directory for autoloading configurations
  tags:
    - full-install
    - light-install
    - neovim
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/"
    state: directory
    recurse: true
    mode: 0o700
    owner: "{{ lookup('env', 'USER') }}"

- name: Install vim-plug
  tags:
    - full-install
    - light-install
    - neovim
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim"
    mode: 0600
    owner: "{{ lookup('env', 'USER') }}"

- name: copy sql-language-server file to .config
  tags:
    - full-install
    - light-install
    - neovim
  ansible.builtin.copy:
    src: sqllsrc.json
    dest: "{{ lookup('env', 'HOME') }}/.config/sql-language-server/"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: 0600

- name: Set neovim as default git editor
  tags:
    - full-install
    - light-install
    - neovim
    - git
  community.general.git_config:
    name: core.editor
    scope: global
    value: nvim
