- name: Install neovim and language servers packages
  tags:
    - full-install
    - light-install
    - neovim
  package:
    name:
      - neovim
      - pyright #python language server
      - bash-language-server #bash language server
    state: present
    update_cache: false
  become: true

- name: Install sql-language-server package
  tags:
    - aur
    - packages
    - light-install
    - full-install
  kewlfft.aur.aur:
    name:
      - sql-language-server
    use: yay
    state: present
    update_cache: yes
  when: ansible_distribution == "Archlinux"

- name: Create neovim directory for autoloading configurations
  tags:
    - full-install
    - light-install
    - neovim
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/autoload/"
    state: directory
    recurse: yes
    mode: 0o700
    owner: "{{ lookup('env', 'USER') }}"

- name: Install vim-plug
  tags:
    - full-install
    - light-install
    - neovim
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/autoload/plug.vim"
    mode: 0600
    owner: "{{ lookup('env', 'USER') }}"

- name: copy sql-language-server file to .config
  tags:
    - full-install
    - light-install
    - neovim
  copy:
    src: sqllsrc.json
    dest: .config/sql-language-server/
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: 0600

- name: Install nvim plugins
  tags:
    - full-install
    - light-install
    - neovim
  ansible.builtin.command: nvim --headless +PlugInstall +qa
# - name: Install Plugins
  # shell: nvim -E -s -c "source /home/frank/.config/nvim/init.vim" -c PlugInstall -c qa
