- name: Install neovim
  tags:
    - full-install
    - light-install
    - neovim
  ansible.builtin.package:
    name:
      - neovim
    state: present
    update_cache: false
  become: true

- name: Install language servers packages
  tags:
    - full-install
    - light-install
    - neovim
  ansible.builtin.package:
    name:
      - pyright #python language server
      - bash-language-server #bash language server
    state: present
    update_cache: false
  become: true
  when: ansible_distribution == "Archlinux"

- name: Install pyright (python language server via snap)
  tags:
    - full-install
    - light-install
    - neovim
  community.general.snap:
    name:
      - pyright
    state: present
    classic: yes
  become: true
  when: ansible_distribution == "Ubuntu"

- name: Install sql-language-server package
  tags:
    - aur
    - never
  kewlfft.aur.aur:
    name:
      - sql-language-server
    use: yay
    state: present
    update_cache: yes
  when: ansible_distribution == "Archlinux"
  ignore_errors: yes

- name: Create neovim directory for autoloading configurations
  tags:
    - full-install
    - light-install
    - neovim
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/autoload/"
    state: directory
    recurse: yes
    mode: 0o700
    owner: "{{ lookup('env', 'USER') }}"

- name: Install vim-plug
  tags:
    - full-install
    - light-install
    - neovim
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/autoload/plug.vim"
    mode: 0600
    owner: "{{ lookup('env', 'USER') }}"

- name: copy sql-language-server file to .config
  tags:
    - full-install
    - light-install
    - neovim
  ansible.builtin.copy:
    src: sqllsrc.json
    dest: .config/sql-language-server/
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: 0600

- name: Install nvim plugins
  tags:
    - full-install
    - light-install
    - neovim
  ansible.builtin.command: nvim --headless +PlugInstall +qa

- name: Install treesitter support for python
  tags:
    - full-install
    - light-install
    - neovim
  ansible.builtin.command: nvim --headless +TSInstall python +qa

- name: Install treesitter support for bash
  tags:
    - full-install
    - light-install
    - neovim
  ansible.builtin.command: nvim --headless +TSInstall bash +qa

- name: Install treesitter support for json
  tags:
    - full-install
    - light-install
    - neovim
  ansible.builtin.command: nvim --headless +TSInstall json +qa

- name: Install treesitter support for markdown
  tags:
    - full-install
    - light-install
    - neovim
  ansible.builtin.command: nvim --headless +TSInstall markdown +qa

- name: Install treesitter support for yaml
  tags:
    - full-install
    - light-install
    - neovim
  ansible.builtin.command: nvim --headless +TSInstall yaml +qa

- name: Install treesitter support for fish
  tags:
    - full-install
    - light-install
    - neovim
  ansible.builtin.command: nvim --headless +TSInstall fish +qa

- name: Install treesitter support for regex
  tags:
    - full-install
    - light-install
    - neovim
  ansible.builtin.command: nvim --headless +TSInstall regex +qa

- name: Install treesitter support for latex
  tags:
    - full-install
    - light-install
    - neovim
  ansible.builtin.command: nvim --headless +TSInstall latex +qa

- name: Install treesitter support for html
  tags:
    - full-install
    - light-install
    - neovim
  ansible.builtin.command: nvim --headless +TSInstall html +qa

- name: Install treesitter support for graphql
  tags:
    - full-install
    - light-install
    - neovim
  ansible.builtin.command: nvim --headless +TSInstall graphql +qa

- name: Install treesitter support for docker
  tags:
    - full-install
    - light-install
    - neovim
  ansible.builtin.command: nvim --headless +TSInstall dockerfile +qa

- name: Install treesitter support for css
  tags:
    - full-install
    - light-install
    - neovim
  ansible.builtin.command: nvim --headless +TSInstall css +qa
