- name: Create neovim directory for autoloading configurations
  tags:
    - full-install
    - light-install
    - neovim
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/autoload/"
    state: directory
    recurse: yes
    mode: 0o700
    owner: "{{ lookup('env', 'USER') }}"

- name: Install vim-plug
  tags:
    - full-install
    - light-install
    - neovim
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/autoload/plug.vim"
    mode: 0o600
    owner: "{{ lookup('env', 'USER') }}"

# - name: Install Plugins
  # shell: nvim -E -s -c "source /home/frank/.config/nvim/init.vim" -c PlugInstall -c qa
