- name: install reflector
  tags:
    - packages
    - full-install
  package:
    name: reflector
  become: true

- name: update pacman mirrorlist
  tags:
    - packages
    - full-install
  script: choose-mirror.sh
  become: true

- name: remove packages
  tags:
    - packages-remove
    - packages
    - full-install
  package:
    name:
      - arch-install-scripts
      - amd-ucode
      - archinstall
      - brltty nano
  state: absent
  update_cache: no

- name: Install packages
  tags:
    - packages-install
    - packages
    - full-install
  package:
    name:
      - htop
      - tmux
      - cronie
  state: present
  update_cache: yes
