- name: install reflector
  tags:
    - full-install
    - light-install
    - packages
  package:
    name: reflector
  become: true
  when: ansible_distribution == "Archlinux"

- name: update pacman mirrorlist
  tags:
    - full-install
    - light-install
    - packages
  script: choose-mirror.sh
  become: true
  when: ansible_distribution == "Archlinux"

- name: copy file pacman.conf to /etc
  tags:
    - full-install
    - light-install
    - packages
  copy:
    src: pacman.conf
    dest: /etc
    owner: root
    group: root
    mode: 0644
  become: true
  when: ansible_distribution == "Archlinux"

- name: Set intel variable when distribution is Archlinux (if necessary)
  tags:
    - processor-intel
    - never
  set_fact:
    intel: intel-ucode
  when: ansible_distribution == "Archlinux"

- name: Set intel variable when distribution is Ubuntu (if necessary)
  tags:
    - processor-intel
    - never
  set_fact:
    intel: intel-acm
  when: ansible_distribution == "Ubuntu"

- name: Install microcode updates for intel (if necessary)
  tags:
    - processor-intel
    - never
  package:
    name: "{{ intel }}"
    state: present
    update_cache: true
  become: true

- name: Set amd variable when distribution is Archlinux (if necessary)
  tags:
    - processor-amd
    - never
  set_fact:
    amd: amd-ucode
  when: ansible_distribution == "Archlinux"

- name: Set amd variable when distribution is Ubuntu (if necessary)
  tags:
    - processor-amd
    - never
  set_fact:
    amd: amd64-microcode
  when: ansible_distribution == "Ubuntu"

- name: Install microcode updates for amd (if necessary)
  tags:
    - processor-amd
    - never
  package:
    name: "{{ amd }}"
    state: present
    update_cache: true
  become: true

- name: Install nvidia drivers
  tags:
    - nvidia
    - never
  package:
    name: nvidia
    state: present
  when: ansible_distribution == "Archlinux"
  become: true

- name: remove packages
  tags:
    - full-install
    - light-install
    - packages
  package:
    name:
      - arch-install-scripts
      - archinstall
      - brltty nano
      - htop
      - vim
      - openvpn
      - grml-zsh-config
      - zsh
      - virtualbox-guest-utils-nox
    state: absent
    update_cache: no
  become: true

- name: Set xorg variable when distribution is Archlinux (if necessary)
  tags:
    - full-install
    - light-install
    - packages
    - xorg
  set_fact:
    xorg:
      - xorg-server
      - xorg-xinit
      - xorg-xsetroot
      - xorg-xrandr
    python_pip: python-pip
    base_devel: base-devel
    wpa_supplicant: wpa_supplicant
    fd: fd
  when: ansible_distribution == "Archlinux"

- name: Set xorg variable when distribution is Ubuntu (if necessary)
  tags:
    - full-install
    - light-install
    - packages
    - xorg
  set_fact:
    xorg:
      - xorg
      - libxrandr2
      - libxrandr-dev
    python_pip: pipenv
    base_devel: make
    wpa_supplicant: wpasupplicant
    fd: fd-find
  when: ansible_distribution == "Ubuntu"

- name: install packages and update cache
  tags:
    - full-install
    - light-install
    - packages
  package:
    name:
      - tmux
      - "{{ xorg[0] }}"
      - "{{ xorg[1] }}"
      - "{{ xorg[2] }}"
      - "{{ xorg[3] }}"
      - xorg-setxkbmap #missing ubuntu
      - xautolock
      - xbindkeys
      - arandr
      - numlockx
      - "{{ python_pip }}"
      - feh
      - dbeaver #missing ubuntu
      - unclutter
      - pamixer #missing ubuntu
      - "{{ base_devel }}"
      - xclip
      - ttf-nerd-fonts-symbols-mono #missing ubuntu
      - ttf-joypixels #missing ubuntu
      - ttf-linux-libertine #missing ubuntu
      - brightnessctl
      - lxappearance
      - arc-gtk-theme #missing ubuntu
      - "{{wpa_supplicant}}"
      - ripgrep
      - "{{ fd }}"
      - fzf
      - baobab
      - nethogs
      - lxsession
      - flameshot
      - clipmenu #missing ubuntu
      - bat
      - dunst
      - trash-cli
      - noto-fonts-emoji #missing ubuntu
      - iwd
    state: latest
    update_cache: yes
  become: true
