- name: install reflector
  tags:
    - packages
    - full-install
  package:
    name: reflector
  become: true

- name: update pacman mirrorlist
  tags:
    - packages
    - full-install
  script: choose-mirror.sh
  become: true

- name: Install packages
  tags:
    - packages-install
    - packages
    - full-install
  package:
    name:
      - htop
      - tmux
      - cronie
  state: present
  update_cache: yes
