- name: install reflector
  tags:
    - packages-install
    - packages
    - full-install
  package:
    name: reflector
  become: true

- name: update pacman mirrorlist
  tags:
    - packages
    - full-install
  script: choose-mirror.sh
  become: true

- name: copy file pacman.conf to /etc
  tags:
    - full-install
  copy:
    src: pacman.conf
    dest: /etc
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Install microcode updates for intel (if necessary)
  tags:
    - processor
    - full-install
  package:
    name: intel-ucode
    state: present
    update_cache: true
  when: processor == "intel"

- name: Install microcode updates for amd (if necessary)
  tags:
    - processor
    - full-install
  package:
    name: amd-ucode
    state: present
    update_cache: true
  when: processor == "amd"

- name: remove packages
  tags:
    - packages-remove
    - packages
    - full-install
  package:
    name:
      - arch-install-scripts
      - amd-ucode
      - archinstall
      - brltty nano
    state: absent
    update_cache: no
  become: true


- name: install packages and update cache
  tags:
    - packages-install
    - packages
    - full-install
  package:
    name:
      - neovim
      - tmux
      - nvidia
      - xorg-server
      - xorg-xinit
      - xorg-xsetroot
      - xorg-xrandr
      - spotifyd
      - xautolock
      - git
      - xbindkeys
      - python-pip
      - feh
      - dbeaver
      - unclutter
      - bluez
      - bluez-tools
      - bluez-utils
      - pulseaudio
      - pulseaudio-bluetooth
      - base-devel
      - xclip
      - ttf-nerd-fonts-symbols-mono
      - brightnessctl
      - alsa-utils
      - pavucontrol
      - lxappearance
      - arc-gtk-theme
      - doas
      - connman
      - wpa_supplicant
      - pamixer
      - ripgrep
      - fd
      - fzf
      - baobab
      - nethogs
      - virt-manager
      - qemu
      - libvirt
      - lxsession
      - spice-vdagent
      - flameshot
      - clipmenu
      - arandr
      - numlockx
      - broadcom-wl
      - bat
      - dunst
    state: latest
    update_cache: yes
  become: true

- name: Clone yay
  tags:
    - aur-install
    - full-install
  git:
    repo: https://aur.archlinux.org/yay-bin.git
    dest: "/home/{{ user }}/.config/yay"
    update: true

- name: Create the `aur_builder` user
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'

- name: Build and install yay
  tags:
    - aur-install
    - full-install
  command:
    chdir: "/home/{{ user }}/.config/yay"
    cmd: "makepkg -sfi --noconfirm"
    creates: /usr/bin/yay

- name: Install aur packages
  tags:
    - aur-packages-install
    - packages-install
    - packages
    - full-install
  kewlfft.aur.aur:
    name:
      - lf
      - brave-bin
      - authy
      - obsidian
      - xflux
      - slack-desktop
      - anki-git
      - spotify
      - insync
      - vscodium-bin
      - google-cloud-sdk
      - google-cloud-sdk-app-engine-python
      - google-cloud-sdk-app-engine-python-extras
      - stremio
      - dashbinsh
      - htim
      - tmux-bash-completion-git
      - checkupdates+aur
      - informant
    use: yay
    state: present
    update_cache: yes
  when: ansible_distribution == "Archlinux"
