- name: install reflector
  tags:
    - full-install
    - light-install
    - packages
  ansible.builtin.package:
    name: reflector
  become: true
  when: ansible_distribution == "Archlinux"

- name: update pacman mirrorlist
  tags:
    - full-install
    - light-install
    - packages
  ansible.builtin.script: choose-mirror.sh
  become: true
  when: ansible_distribution == "Archlinux"

- name: copy file pacman.conf to /etc
  tags:
    - full-install
    - light-install
    - packages
  ansible.builtin.copy:
    src: pacman.conf
    dest: /etc
    owner: root
    group: root
    mode: 0644
  become: true
  when: ansible_distribution == "Archlinux"

- name: Set intel variable when distribution is Archlinux (if necessary)
  tags:
    - full-install
    - light-install
    - packages
  ansible.builtin.set_fact:
    intel: intel-ucode
  when: ansible_distribution == "Archlinux" and "GenuineIntel" in ansible_processor

- name: Set intel variable when distribution is Ubuntu (if necessary)
  tags:
    - full-install
    - light-install
    - packages
  ansible.builtin.set_fact:
    intel: intel-acm
  when: ansible_distribution == "Ubuntu" and "GenuineIntel" in ansible_processor

- name: Install microcode updates for intel (if necessary)
  tags:
    - full-install
    - light-install
    - packages
  ansible.builtin.package:
    name: "{{ intel }}"
    state: present
    update_cache: true
  become: true

- name: Set amd variable when distribution is Archlinux (if necessary)
  tags:
    - full-install
    - light-install
    - packages
  ansible.builtin.set_fact:
    amd: amd-ucode
  when: ansible_distribution == "Archlinux" and "AuthenticAMD" in ansible_processor

- name: Set amd variable when distribution is Ubuntu (if necessary)
  tags:
    - processor-amd
    - never
  ansible.builtin.set_fact:
    amd: amd64-microcode
  when: ansible_distribution == "Ubuntu" and "AuthenticAMD" in ansible_processor

- name: Install microcode updates for amd (if necessary)
  tags:
    - processor-amd
    - never
  ansible.builtin.package:
    name: "{{ amd }}"
    state: present
    update_cache: true
  become: true

- name: Install nvidia drivers
  tags:
    - nvidia
    - never
  ansible.builtin.package:
    name: nvidia
    state: present
  when: ansible_distribution == "Archlinux"
  become: true

- name: remove packages
  tags:
    - full-install
    - light-install
    - packages
  ansible.builtin.package:
    name:
      - arch-install-scripts
      - archinstall
      - brltty
      - nano
      - htop
      - vim
      - openvpn
      - grml-zsh-config
      - zsh
      - virtualbox-guest-utils-nox
    state: absent
    update_cache: no
  become: true

- name: Set xorg variable when distribution is Archlinux (if necessary)
  tags:
    - full-install
    - light-install
    - packages
    - xorg
  ansible.builtin.set_fact:
    xorg:
      - xorg-server
      - xorg-xinit
      - xorg-xsetroot
      - xorg-xrandr
      - xorg-setxkbmap
    python_pip: python-pip
    base_devel: base-devel
    wpa_supplicant: wpa_supplicant
    fd: fd
  when: ansible_distribution == "Archlinux"

- name: Set xorg variable when distribution is Ubuntu (if necessary)
  tags:
    - full-install
    - light-install
    - packages
    - xorg
  ansible.builtin.set_fact:
    xorg:
      - xorg
      - libxrandr2
      - libxrandr-dev
      - xorg
      - xorg
    python_pip: pipenv
    base_devel: make
    wpa_supplicant: wpasupplicant
    fd: fd-find
  when: ansible_distribution == "Ubuntu"

- name: Set rfkill variable when distribution is Archlinux (if necessary)
  tags:
    - full-install
    - light-install
    - packages
    - xorg
  ansible.builtin.set_fact:
    rfkill:
      - util-linux
    python_pip: python-pip
    base_devel: base-devel
    wpa_supplicant: wpa_supplicant
    fd: fd
  when: ansible_distribution == "Archlinux"

- name: Set rfkill variable when distribution is Ubuntu (if necessary)
  tags:
    - full-install
    - light-install
    - packages
    - xorg
  ansible.builtin.set_fact:
    rfkill:
      - rfkill
    python_pip: pipenv
    base_devel: make
    wpa_supplicant: wpasupplicant
    fd: fd-find
  when: ansible_distribution == "Ubuntu"

- name: purge snapd in Ubuntu
  tags:
    - full-install
    - light-install
    - packages
  ansible.builtin.package:
    name:
      - snapd
    state: absent
  become: true
  when: ansible_distribution == "Ubuntu"

- name: install packages and update cache
  tags:
    - full-install
    - light-install
    - packages
  ansible.builtin.package:
    name:
      - tmux
      - "{{ xorg[0] }}"
      - "{{ xorg[1] }}"
      - "{{ xorg[2] }}"
      - "{{ xorg[3] }}"
      - "{{ xorg[4] }}"
      - xautolock
      - xbindkeys
      - arandr
      - numlockx
      - "{{ python_pip }}"
      - feh
      - unclutter
      - "{{ base_devel }}"
      - xclip
      - brightnessctl
      - lxappearance #Program to set theme for gtk applications
      - "{{wpa_supplicant}}"
      - ripgrep
      - "{{ fd }}"
      - fzf
      - baobab
      - nethogs
      - lxsession
      - flameshot
      - bat
      - dunst
      - trash-cli
      - qt5ct #To set theme for qt applications
      - man-db #Manpages
      - "{{rfkill}}"
      - csvkit
    state: latest
    update_cache: yes
  become: true

- name: install packages that i still have not set in ubuntu
  tags:
    - full-install
    - light-install
    - packages
  ansible.builtin.package:
    name:
      - pamixer #missing ubuntu
      - ttf-nerd-fonts-symbols-mono #missing ubuntu
      - ttf-joypixels #missing ubuntu
      - ttf-linux-libertine #missing ubuntu
      - arc-gtk-theme #missing ubuntu
      - clipmenu #missing ubuntu
      - noto-fonts-emoji #missing ubuntu
    state: latest
    update_cache: yes
  become: true
  when: ansible_distribution == "Archlinux"
