- name: Install aur packages
  tags:
    - full-install
    - light-install
    - preload
  kewlfft.aur.aur:
    name:
      - preload
    use: yay
    state: present
    update_cache: yes
  when: ansible_distribution == "Archlinux"

- name: copy file preload.conf to /etc
  tags:
    - full-install
    - light-install
    - preload
  copy:
    src: preload.conf
    dest: /etc
    owner: root
    group: root
    mode: 0644
  become: yes

- name: start preload
  tags:
    - full-install
    - light-install
    - preload
  ansible.builtin.service:
    name: preload
    state: started
    enabled: yes
  become: yes
