- name: copy file preload.conf to /etc
  tags:
    - full-install
    - preload
  copy:
    src: preload.conf
    dest: /etc
    owner: root
    group: root
    mode: 0644
  become: yes

- name: start preload
  tags:
    - start-services
    - full-install
  ansible.builtin.service:
    name: preload
    state: started
    enabled: yes
  become: yes
