- name: Install preload package
  tags:
    - full-install
    - light-install
    - preload
  kewlfft.aur.aur:
    name:
      - preload
    use: yay
    state: present
    update_cache: yes
  when: ansible_distribution == "Archlinux"
  ignore_errors: yes
  notify: start preload


- name: Install preload package
  tags:
    - full-install
    - light-install
    - preload
  package:
    name:
      - preload
    state: present
  become: true
  when: ansible_distribution == "Ubuntu"
  notify: start preload

- name: copy file preload.conf to /etc
  tags:
    - full-install
    - light-install
    - preload
  copy:
    src: preload.conf
    dest: /etc
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: restart preload

handlers:
  - name: start preload
    tags:
      - full-install
      - light-install
      - preload
    ansible.builtin.service:
      name: preload
      state: started
      enabled: yes
    become: yes

  - name: restart preload
    tags:
      - full-install
      - light-install
      - preload
    ansible.builtin.service:
      name: preload
      state: restarted
      enabled: yes
    become: yes
