- name: disable root login
  tags:
    - full-install
    - light-install
    - security
  user:
    name: root
    shell: /sbin/nologin
  become: yes

- name: Disable root login via ssh
  tags:
    - full-install
    - light-install
    - security
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: "PermitRootLogin no"
    state: present
    backup: yes
  become: yes
  notify:
    - restart ssh

handlers:
  - name: restart ssh
    systemctl:
      name: sshd
      state: restarted
    become: yes
