---
- name: disable root login
  tags:
    - full-install
    - light-install
    - security
  ansible.builtin.user:
    name: root
    shell: /sbin/nologin
  become: true

- name: install fail2ban
  tags:
    - full-install
    - light-install
    - security
    - fail2ban
  ansible.builtin.package:
    name: fail2ban
  become: true
  when: ansible_distribution == "Archlinux"
  notify: "start fail2ban"

- name: Copy fail2ban configuration file
  tags:
    - full-install
    - light-install
    - security
    - fail2ban
  ansible.builtin.copy:
    src: jail.local
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644
  become: true
  notify: "start fail2ban"

- name: install apparmor
  tags:
    - full-install
    - light-install
    - security
    - apparmor
  ansible.builtin.package:
    name: apparmor
  become: true
  when: ansible_distribution == "Archlinux"
  notify: "start apparmor"

- name: Enable apparmor in kernel parameters
  tags:
    - full-install
    - light-install
    - security
    - apparmor
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '.*GRUB_CMDLINE_LINUX_DEFAULT=.*'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="loglevel=3 quiet lsm=landlock,lockdown,yama,integrity,apparmor,bpf"'
    backrefs: true
  become: true
  notify: update grub
