- name: start services
  tags:
    - start-services
    - full-install
  ansible.builtin.service:
    name:
      - iwd
      - libvirt
      - bluetooth
      - cronie.service
    state: started
    enabled: yes
  become: yes
