- name: start iwd
  tags:
    - start-services
    - full-install
  ansible.builtin.service:
    name: iwd
    state: started
    enabled: yes
  become: yes

- name: start libvirt
  tags:
    - start-services
    - full-install
  ansible.builtin.service:
    name: libvirtd
    state: started
    enabled: yes
  become: yes

- name: start bluetooth
  tags:
    - start-services
    - full-install
  ansible.builtin.service:
    name: bluetooth
    state: started
    enabled: yes
  become: yes

- name: start cron
  tags:
    - start-services
    - full-install
  ansible.builtin.service:
    name: cronie
    state: started
    enabled: yes
  become: yes
