- name: start iwd
  tags:
    - start-services
    - full-install
    - light-install
  ansible.builtin.service:
    name: iwd
    state: started
    enabled: yes
  become: yes

- name: start bluetooth
  tags:
    - start-services
    - full-install
    - light-install
  ansible.builtin.service:
    name: bluetooth
    state: started
    enabled: yes
  become: yes

- name: start preload
  tags:
    - start-services
    - full-install
  ansible.builtin.service:
    name: preload
    state: started
    enabled: yes
  become: yes

- name: restart connman
  tags:
    - start-services
    - full-install
    - light-install
  ansible.builtin.service:
    name: connman
    state: restarted
    enabled: yes
  become: yes
