- name: stop systemd-networkd
  tags:
    - stop-services
    - full-install
    - light-install
  ansible.builtin.service:
    name: systemd-networkd
    state: stopped
    enabled: no
  become: yes
