- name: Install timeshift packages
  tags:
    - aur-packages-install
    - packages-install
    - packages
    - full-install
    - timeshift
  kewlfft.aur.aur:
    name:
      - timeshift
      - timeshift-autosnap
    use: yay
    state: present
    update_cache: yes
  when: ansible_distribution == "Archlinux"

- name: copy file timeshift.json to /etc
  tags:
    - full-install
    - timeshift
    - light-install
  copy:
    src: timeshift.json
    dest: /etc/timeshift/
    owner: root
    group: root
    mode: 0666
  become: yes
