---
- name: Install timeshift packages
  tags:
    - full-install
    - light-install
    - timeshift
  kewlfft.aur.aur:
    name:
      - timeshift
      - timeshift-autosnap
    use: yay
    state: present
    update_cache: yes
  when: ansible_distribution == "Archlinux"
  ignore_errors: yes

- name: copy file timeshift.json to /etc
  tags:
    - full-install
    - light-install
    - timeshift
  ansible.builtin.copy:
    src: timeshift.json
    dest: /etc/timeshift/
    owner: root
    group: root
    mode: 0666
  become: yes
