---
- name: install tlp packages
  tags:
    - full-install
    - light-install
    - tlp
  ansible.builtin.package:
    name:
      - tlp # Power managment for laptop battery
    state: present
    update_cache: false
  become: true
  notify: restart tlp
