- name: create ansible user
  tags:
    - full-install
    - user-create
  user:
    name: ansible
    system: yes

- name: "create {{ user }} user"
  tags:
    - full-install
    - user-create
  user:
    name: "{{ user }}"
    groups: root

- name: copy sudoers_ansible
  tags:
    - full-install
    - user-create
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'sudoers_ansible', dest: '/etc/sudoers.d/ansible' }
    - { src: 'sudoers_frank', dest: '/etc/sudoers.d/frank' }
