---
- name: Mark oh-my-fish installed with /etc/omf.installed
  tags:
    - fish
  ansible.builtin.file:
    path: /etc/omf.installed
    mode: "0644"
    state: touch
  become: true

- name: Restart fail2ban
  tags:
    - security
    - fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
    enabled: true
  become: true
  listen: start fail2ban

- name: Run grub-mkconfig
  tags:
    - grub
  ansible.builtin.command: grub-mkconfig -o /boot/grub/grub.cfg
  become: true
  listen: update grub
  register: base_grub_update
  changed_when: base_grub_update.rc != 0

- name: Restart ssh
  tags:
    - security
    - ssh
  ansible.builtin.service:
    name: sshd
    state: restarted
  become: true
  listen: restart ssh

- name: Restart auditd
  tags:
    - security
    - apparmor
  ansible.builtin.service:
    name: auditd
    state: restarted
    enabled: true
  become: true

- name: Restart apparmor
  tags:
    - security
    - apparmor
  ansible.builtin.service:
    name: apparmor
    state: restarted
    enabled: true
  become: true
  listen: start apparmor

# Tailscale handlers

- name: Restart tailscale service
  tags:
    - tailscale
  ansible.builtin.service:
    name: tailscale
    state: restarted
    enabled: true
  become: true

- name: Fetch Tailscale status
  listen: Confirm Tailscale is Connected
  ansible.builtin.command: tailscale status --json
  changed_when: false
  register: base_tailscale_status

- name: Parse status JSON
  listen: Confirm Tailscale is Connected
  vars:
    base_status: "{{ base_tailscale_status.stdout | from_json }}"
  ansible.builtin.set_fact:
    base_tailscale_is_online: "{{ base_status.Self.Online }}"

- name: Tailscale online status
  listen: Confirm Tailscale is Connected
  ansible.builtin.debug:
    msg: "Online: {{ base_tailscale_is_online }}"
  when: verbose

- name: Assert Tailscale is Connected
  listen: Confirm Tailscale is Connected
  ansible.builtin.assert:
    that:
      - base_tailscale_is_online

- name: Restart qemu-guest-agent
  ansible.builtin.service:
    name: qemu-guest-agent
    state: restarted
    enabled: true
  become: true
  when: ansible_virtualization_role == "guest"

- name: Restart sysstat
  ansible.builtin.service:
    name: sysstat
    state: restarted
    enabled: true
  become: true
  listen: start sysstat
