---
- name: Install DBeaver package
  tags:
    - full-install
    - light-install
    - packages
    - dbeaver
  ansible.builtin.package:
    name: dbeaver # missing ubuntu
    state: present
    update_cache: false
  become: true

- name: Ensure dbeaver directory exists in .config
  tags:
    - full-install 
    - light-install 
    - libvirt
  ansible.builtin.file:
    dest: "{{ lookup('env', 'HOME') }}/.local/share/DBeaverData/workspace6/General/.dbeaver/"  
    mode: 0770
    owner: "{{ lookup('env', 'USER') }}"
    state: directory

- name: Copy DBeaver configuration files 
  tags:
    - full-install
    - light-install
    - dbeaver
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ lookup('env', 'USER') }}"
    mode: 0644
  loop:
    - { src: "data-sources.json", dest: "{{ lookup('env', 'HOME') }}/.local/share/DBeaverData/workspace6/General/.dbeaver" }
    - { src: "project-metadata.json", dest: "{{ lookup('env', 'HOME') }}/.local/share/DBeaverData/workspace6/General/.dbeaver" }
