---
- name: Ensure gdrive-pessoal, not-up and iso directories exists.
  tags:
    - full-install
    - light-install
    - directories
  ansible.builtin.file:
    dest: "{{ ansible_env.HOME }}/gdrive-pessoal/not-up/iso"
    mode: 0770
    state: directory
