---
- name: Ensure gdrive-pessoal, not-up and iso directories exists.
  tags:
    - full-install
    - light-install
    - directories
  ansible.builtin.file:
    dest: "{{ lookup('env', 'HOME') }}/gdrive-pessoal/not-up/iso"
    mode: 0770
    group: "{{ lookup('env', 'USER') }}"
    owner: "{{ lookup('env', 'USER') }}"
    state: directory
