---
- name: Cloning .dotfiles
  tags:
    - full-install
    - light-install
    - dotfiles
  ansible.builtin.git:
    version: main
    repo: git@github.com:andre-gonzalez/dotfiles.git
    dest: "{{ ansible_env.HOME }}/.config/dotfiles"
    recursive: true
    update: true
    bare: true
    accept_hostkey: true
  notify: set up dotfiles
