---
# - name: copy file grub config file
#   tags:
#     - full-install
#     - light-install
#     - grub
#   ansible.builtin.copy:
#     src: grub
#     dest: /etc/default
#     owner: root
#     group: root
#     mode: 0644
#   become: true
#   when: ansible_distribution == "Archlinux"

- name: install grub
  tags:
    - full-install
    - light-install
    - grub
  ansible.builtin.package:
    name: grub
  become: true
  when: ansible_distribution == "Archlinux"

- name: Change grub timeout to 0 second
  tags:
    - full-install
    - light-install
    - grub
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '.*GRUB_TIMEOUT=.*'
    line: 'GRUB_TIMEOUT=0'
    backrefs: true
  become: true
  register: update_grub

- name: Change grub timeout to hidden
  tags:
    - full-install
    - light-install
    - grub
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '.*GRUB_TIMEOUT_STYLE=.*'
    line: 'GRUB_TIMEOUT_STYLE=hidden'
    backrefs: true
  become: true
  register: update_grub2

- name: Speed up linux systems for workstations disabling mitigations - https://christitus.com/speedup-linux/
  tags:
    - full-install
    - light-install
    - grub
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '.*GRUB_CMDLINE_LINUX=.*'
    line: 'GRUB_CMDLINE_LINUX="mitigations=off"'
    backrefs: true
  become: true
  when: ansible_memtotal_mb > 16000
  register: update_grub3

- name: Speed up linux systems for workstations disabling mitigations and enable zswap compression - https://christitus.com/speedup-linux/
  tags:
    - full-install
    - light-install
    - grub
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '.*GRUB_CMDLINE_LINUX=.*'
    line: 'GRUB_CMDLINE_LINUX="zswap.enabled=1 mitigations=off"'
    backrefs: true
  become: true
  when: ansible_memtotal_mb <= 16000
  register: update_grub4

- name: Set grub to keep the latest kernel that were started (LTS or Bleeding edge)
  tags:
    - full-install
    - light-install
    - grub
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '.*GRUB_DEFAULT=.*'
    line: 'GRUB_DEFAULT=saved'
    backrefs: true
  become: true
  register: update_grub5

- name: Set grub to keep the latest kernel that were started (LTS or Bleeding edge)
  tags:
    - full-install
    - light-install
    - grub
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '.*GRUB_SAVEDEFAULT=.*'
    line: 'GRUB_SAVEDEFAULT=true'
    backrefs: true
  become: true
  register: update_grub6

- name: copy file update-grub
  tags:
    - full-install
    - light-install
    - grub
  ansible.builtin.copy:
    src: update-grub
    dest: /usr/bin
    owner: root
    group: root
    mode: 0755
  become: true
  when: update_grub is changed or update_grub2 is changed or update_grub3 is changed or update_grub4 is changed or update_grub5 is changed or update_grub6 is changed
