---
- name: Uninstall iptables so it can install iptables-nft later
  tags:
    - full-install
    - light-install
    - libvirt
  ansible.builtin.package:
    name: iptables
    state: absent
    update_cache: false
    force: true
  become: true

- name: Install KVM/QEMU packages
  tags:
    - full-install
    - light-install
    - libvirt
  ansible.builtin.package:
    name:
      - qemu-base
      - libvirt
      - virt-manager
      - spice-vdagent
      - dnsmasq
      - ebtables
    state: present
    update_cache: false
  become: true
  notify: "finish libvirt configuration"

- name: Ensure group libvirt exists
  tags:
    - full-install
    - light-install
    - libvirt
  ansible.builtin.group:
    name: libvirtd
    state: present
  become: true

- name: add the user {{ lookup('env', 'USER') }} to the libvirt group
  tags:
    - full-install
    - light-install
    - libvirt
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    group: libvirtd
  become: true
  notify: "finish libvirt configuration"

- name: copy file qemu.conf to /etc/libvirt
  tags:
    - full-install
    - light-install
    - libvirt
  ansible.builtin.copy:
    src: qemu.conf
    dest: /etc/libvirt
    owner: root
    group: root
    mode: 0644
  become: true
  notify: "finish libvirt configuration"

- name: change libvirt.conf to allow non root user to start a VM
  tags:
    - full-install
    - light-install
    - libvirt
  ansible.builtin.lineinfile:
    path: /etc/libvirt/libvirt.conf
    state: present
    line: 'uri_default = "qemu:///system"'
  become: true

- name: Copy libvirt conf to user .config directory
  tags:
    - full-install
    - light-install
    - libvirt
  ansible.builtin.copy:
    src: /etc/libvirt/libvirt.conf
    dest: "{{ ansible_env.HOME }}/.config/libvirt/libvirt.conf"
    mode: 0644
  become: true
