---
- name: Clone linux-scripts
  tags:
    - full-install
    - light-install
    - scripts
  ansible.builtin.git:
    version: main
    repo: git@github.com:andre-gonzalez/linux-scripts.git
    dest: "{{ ansible_env.HOME }}/.scripts"
    accept_hostkey: true
  ignore_errors: true

- name: Copy files to .scripts
  tags:
    - full-install
    - light-install
    - scripts
  ansible.builtin.copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'qrc', dest: "{{ ansible_env.HOME }}/.scripts", mode: 0700 }
    - { src: 'qso', dest: "{{ ansible_env.HOME }}/.scripts", mode: 0700 }
    - { src: 'salesops-dw-access', dest: "{{ ansible_env.HOME }}/.scripts/.env/", mode: 0600 }
    - { src: 'redeciclo-corp-access', dest: "{{ ansible_env.HOME }}/.scripts/.env/", mode: 0600 }
    - { src: 'instapaper', dest: "{{ ansible_env.HOME }}/.scripts/.env/", mode: 0600 }
