---
- include_tasks: tasks/debug.yml
  tags:
    - debug
    - never
- include_tasks: tasks/directory.yml
  tags:
    - full-install
    - light-install
    - directories
- include_tasks: tasks/ssh.yml
  tags:
    - full-install
    - light-install
    - ssh
- include_tasks: tasks/grub.yml
  tags:
    - full-install
    - light-install
    - grub
- include_tasks: tasks/systemd.yml
  tags:
    - full-install
    - light-install
    - systemd
- include_tasks: tasks/ansible.yml
  tags:
    - full-install
    - light-install
    - users
    - ansible
- include_tasks: tasks/audio.yml
  tags:
    - full-install
    - light-install
    - pipewire
    - pulseaudio
- include_tasks: tasks/cron.yml
  tags:
    - full-install
    - light-install
    - cron
    - auto-adjust-brightness
- include_tasks: tasks/git.yml
  tags:
    - full-install
    - light-install
    - git
- include_tasks: tasks/dotfiles.yml
  tags:
    - full-install
    - light-install
    - dotfiles
- include_tasks: tasks/linux-scripts.yml
  tags:
    - full-install
    - light-install
    - scripts
- include_tasks: tasks/bluetooth.yml
  tags:
    - full-install
    - light-install
    - bluetooth
    - pulseaudio
- include_tasks: tasks/packages.yml
  tags:
    - full-install
    - light-install
    - packages
    - nvidia
- include_tasks: tasks/dwm.yml
  tags:
    - full-install
    - light-install
    - dwm
- include_tasks: tasks/st.yml
  tags:
    - full-install
    - light-install
    - st
- include_tasks: tasks/dmenu.yml
  tags:
    - full-install
    - light-install
    - dmenu
- include_tasks: tasks/dwmstatus.yml
  tags:
    - full-install
    - light-install
    - dwmblocks
- include_tasks: tasks/slock.yml
  tags:
    - full-install
    - light-install
    - slock
- include_tasks: tasks/eureciclo.yml
  tags:
    - full-install
    - light-install
    - eureciclo
- include_tasks: tasks/anki.yml
  tags:
    - full-install
    - light-install
    - anki
- include_tasks: tasks/aws.yml
  tags:
    - full-install
    - light-install
    - aws
- include_tasks: tasks/stw.yml
  tags:
    - full-install
    - light-install
    - stw
- include_tasks: tasks/wall-d.yml
  tags:
    - full-install
    - light-install
    - wall-d
- include_tasks: tasks/docker.yml
  tags:
    - full-install
    - docker
- include_tasks: tasks/dbeaver.yml
  tags:
    - full-install
    - light-install
    - dbeaver
- include_tasks: tasks/collections-install.yml
  tags:
    - full-install
    - light-install
    - aur
    - collections-install
    - ufw
- include_tasks: tasks/aur-packages.yml
  tags:
    - aur
    - never
- include_tasks: tasks/libvirt.yml
  tags:
    - full-install
    - libvirt
- include_tasks: tasks/windows-vm.yml
  tags:
    - full-install
    - collections-install
    - windows-vm
    - aur
- include_tasks: tasks/databricks.yml
  tags:
    - full-install
    - light-install
    - databricks
    - aur
# - include_tasks: tasks/drives.yml
#   tags:
#     - full-install
#     - light-install
#     - drives
#     - samsung-expert
- include_tasks: tasks/rsync.yml
  tags:
    - full-install
    - light-install
    - rsync
# - include_tasks: tasks/samba.yml
#   tags:
#     - never
#     - samba
- include_tasks: tasks/neovim.yml
  tags:
    - full-install
    - light-install
    - neovim
    - git
    - aur
- include_tasks: tasks/network.yml
  tags:
    - full-install
    - light-install
    - network
    - netbook
    - samsung-expert
    - aur
- include_tasks: tasks/save-battery.yml
  tags:
    - full-install
    - light-install
    - save-battery
    - tlp
    - powertop
    - aur
    - samsung-expert
- include_tasks: tasks/dwmblocks.yml
  tags:
    - full-install
    - light-install
    - dwmblocks
    - aur
- include_tasks: tasks/terraform.yml
  tags:
    - full-install
    - light-install
    - aur
    - terraform
    - neovim
- include_tasks: tasks/gcloud.yml
  tags:
    - gcloud
    - aur
- include_tasks: tasks/lfub.yml
  tags:
    - never
    - aur
    - lf
- include_tasks: tasks/preload.yml
  tags:
    - never
    - aur
    - preload
- include_tasks: tasks/brave.yml
  tags:
    - never
    - aur
    - brave
- include_tasks: tasks/timeshift.yml
  tags:
    - never
    - aur
    - timeshift
# - include_tasks: tasks/smtpd.yml
#   tags:
#     - never
#     - opensmtpd
- include_tasks: tasks/aur-packages2.yml
  tags:
    - aur
    - never
# - include_tasks: tasks/portmaster.yml
#   tags:
#     - aur
#     - never
#     - portmaster
- include_tasks: tasks/doas.yml
  tags:
    - full-install
    - light-install
    - doas
- include_tasks: tasks/pritunl-vpn.yml
  tags:
    - full-install
    - light-install
    - pritunl-vpn
    - eureciclo
