---
- name: Install wireless drivers (samsung-expert)
  tags:
    - samsung-expert
    - never
  ansible.builtin.package:
    name:
      - broadcom-wl
      - iwd
    state: present
    update_cache: false
  when: ansible_distribution in ["Archlinux"]
  become: true
  notify: "restart network"
