---
- name: Install preload package when distribution is Archlinux
  tags:
    - full-install
    - light-install
    - preload
  kewlfft.aur.aur:
    name:
      - preload
    use: yay
    state: present
    update_cache: true
  when: ansible_distribution == "Archlinux"
  ignore_errors: true
  register: restart_preload

- name: Install preload package when distribution is Ubuntu
  tags:
    - full-install
    - light-install
    - preload
  ansible.builtin.package:
    name:
      - preload
    state: present
  become: true
  when: ansible_distribution == "Ubuntu"
  register: restart_preload2

- name: copy file preload.conf to /etc
  tags:
    - full-install
    - light-install
    - preload
  ansible.builtin.copy:
    src: preload.conf
    dest: /etc
    owner: root
    group: root
    mode: 0644
  become: true
  register: restart_preload3

- name: restart preload
  tags:
    - full-install
    - light-install
    - preload
  ansible.builtin.service:
    name: preload
    state: restarted
    enabled: true
  become: true
  when: restart_preload is changed or restart_preload2 is changed or restart_preload3 is changed
