---
- name: Install samba packages
  tags:
    - samba
    - never
  ansible.builtin.package:
    name:
      - krb5
      - ntp
      - python-dnspython
      - openresolv
      - samba
  become: true
  when: ansible_distribution == "Archlinux"

- name: Ensure group sambausers exists
  tags:
    - samba
    - never
  ansible.builtin.group:
    name: sambausers
    state: present
  become: true

- name: Ensure /samba directory exists
  tags:
    - samba
    - never
  ansible.builtin.file:
    dest: "/samba"
    group: sambausers
    mode: 1770
    state: directory
  become: true

- name: Copy file smb.conf to /etc/samba/
  tags:
    - samba
    - never
  ansible.builtin.copy:
    src: smb.conf
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: 0644
  become: true
  notify: "finish samba configuration"

- name: File to Allow samba in ufw
  tags:
    - samba
    - never
  ansible.builtin.copy:
    src: samba-ufw
    dest: /etc/ufw/applications.d/samba
    owner: root
    group: root
    mode: 0644
  become: true

- name: Allow samba in ufw
  tags:
    - samba
    - never
  community.general.ufw:
    rule: allow
    name: Samba
  become: true
