---
- name: Install ssh key
  tags:
    - full-install
    - light-install
    - ssh
  ansible.builtin.copy:
    src: personal_id_ed25519_2023-05
    dest: "{{ lookup('env', 'HOME') }}/.ssh"
    owner: "{{ lookup('env', 'USER') }}"
    mode: 0600

- name: Install eureciclo VM ssh key
  tags:
    - full-install
    - light-install
    - ssh
  ansible.builtin.copy:
    src: eureciclo-2023-06
    dest: "{{ lookup('env', 'HOME') }}/.ssh"
    owner: "{{ lookup('env', 'USER') }}"
    mode: 0600

- name: Install ssh key public
  tags:
    - full-install
    - light-install
    - ssh
  ansible.builtin.copy:
    src: personal_id_ed25519_2023-05.pub
    dest: "{{ lookup('env', 'HOME') }}/.ssh"
    mode: 0644
    owner: "{{ lookup('env', 'USER') }}"
  notify: "secure ssh"

- name: Copy config file
  tags:
    - full-install
    - light-install
    - ssh
  ansible.builtin.copy:
    src: config
    dest: "{{ lookup('env', 'HOME') }}/.ssh"
    mode: 0600
    owner: "{{ lookup('env', 'USER') }}"
  notify: "secure ssh"
