---
- name: Extract anki files
  tags:
    - full-install
    - light-install
    - anki
  ansible.builtin.unarchive:
    src:  "{{ lookup('env', 'HOME') }}/.config/anki/anki-installer.tar.zst"
    dest: "{{ lookup('env', 'HOME') }}/.config/anki"
  listen: proceed anki installation

- name: Install anki
  tags:
    - full-install
    - light-install
    - anki
  ansible.builtin.script:
    chdir: "{{ lookup('env', 'HOME') }}/.config/anki/anki-2.1.53-linux-qt6"
    cmd:  "{{ lookup('env', 'HOME') }}/.config/anki/anki-2.1.53-linux-qt6/install.sh"
  become: true
  listen: proceed anki installation

- name: restart systemd-networkd
  tags:
    - full-install
    - light-install
    - network
  ansible.builtin.service:
    name: systemd-networkd
    state: restarted
    enabled: yes
  become: yes
  listen: "restart network"

- name: start iwd
  tags:
    - full-install
    - light-install
    - network
  ansible.builtin.service:
    name: iwd
    state: restarted
    enabled: yes
  become: yes
  listen: "restart network"

- name: restart libvirt
  tags:
    - full-install
    - light-install
    - libvirt
  ansible.builtin.service:
    name: libvirtd
    state: restarted
    enabled: yes
  become: yes

- name: Disable root login via ssh
  tags:
    - full-install
    - light-install
    - security
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: "PermitRootLogin no"
    state: present
    backup: yes
  become: yes
  listen: "secure ssh"

- name: Disable password login via ssh
  tags:
    - full-install
    - light-install
    - security
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: "PasswordAuthentication no"
    state: present
    backup: yes
  become: yes
  listen: "secure ssh"

- name: restart ssh
  systemctl:
    name: sshd
    state: restarted
  become: yes
  listen: "secure ssh"

- name: restart preload
  tags:
    - full-install
    - light-install
    - preload
  ansible.builtin.service:
    name: preload
    state: restarted
    enabled: yes
  become: yes
