---
- name: Set zathura as default pdf reader
  ansible.builtin.command: xdg-mime default org.pwmt.zathura.desktop application/pdf
  register: zathura_xdg_mine
  changed_when: zathura_xdg_mine.rc != 2

- name: Extract anki files
  ansible.builtin.unarchive:
    src: "{{ lookup('env', 'HOME') }}/.config/anki/anki-installer.tar.zst"
    dest: "{{ lookup('env', 'HOME') }}/.config/anki/install-files"
  listen: proceed_anki_installation

- name: Install anki
  ansible.builtin.command:
    chdir: "{{ lookup('env', 'HOME') }}/.config/anki/install-files/{{ json_reponse.json.assets.2.name | regex_replace( '\\.\\w*\\.\\w*$', '')  }}"
    cmd: ./install.sh
  become: true
  listen: proceed_anki_installation
  register: anki_install
  changed_when: anki_install.rc != 2

- name: Set up dotfiles
  tags:
    - dotfiles
  ansible.builtin.command: /usr/bin/git --git-dir={{ lookup('env', 'HOME') }}/.config/dotfiles/ --work-tree={{ lookup('env', 'HOME') }} checkout -f
  listen: set_up_dotfiles
  register: dotfiles_set
  changed_when: dotfiles_set.rc != 2

- name: Install wall-d
  tags:
    - wall-d
  ansible.builtin.command: ./install.sh
  args:
    chdir: "{{ lookup('env', 'HOME') }}/.config/wall-d/"
  listen: install_wall-d
  register: wall_d_installed
  changed_when: wall_d_installed.rc != 2

- name: Start iwd
  tags:
    - wifi
  ansible.builtin.service:
    name: iwd
    state: restarted
    enabled: true
  become: true
  listen: restart_network is changed

- name: Restart systemd-networkd
  tags:
    - network
  ansible.builtin.service:
    name: systemd-networkd
    state: restarted
    enabled: true
  become: true
  when: restart_network is changed
