---
- name: Ensure anki directory exists
  tags:
    - anki
  ansible.builtin.file:
    dest: "{{ lookup('env', 'HOME') }}/.config/anki/install-files"
    mode: '0700'
    state: directory

- name: Get latest anki release
  tags:
    - anki
  ansible.builtin.uri:
    url: https://api.github.com/repos/ankitects/anki/releases/latest
    return_content: true
  register: json_reponse

- name: Download anki installer
  tags:
    - anki
  ansible.builtin.get_url:
    url: "{{ json_reponse.json.assets.2.browser_download_url }}"
    dest: "{{ lookup('env', 'HOME') }}/.config/anki/anki-installer.tar.zst"
    force: true
    mode: '0777'
  register: "proceed_anki_installation"

- name: Extract anki files
  tags:
    - anki
  ansible.builtin.unarchive:
    src: "{{ lookup('env', 'HOME') }}/.config/anki/anki-installer.tar.zst"
    dest: "{{ lookup('env', 'HOME') }}/.config/anki/install-files"
  when: proceed_anki_installation is changed

- name: Install anki
  tags:
    - anki
  ansible.builtin.shell:
    chdir: "{{ lookup('env', 'HOME') }}/.config/anki/install-files/{{ json_reponse.json.assets.2.name | regex_replace( '\\.\\w*\\.\\w*$', '')  }}"
    cmd: ./install.sh
  become: true
  when: proceed_anki_installation is changed
