---
- name: Ansible | Clone ansible repository
  tags:
    - ansible
  ansible.builtin.git:
    version: main
    repo: git@github.com:andre-gonzalez/ansible.git
    key_file: "{{ lookup('env', 'HOME') }}/.ssh/personal_id_ed25519_2023-11"
    dest: "{{ lookup('env', 'HOME') }}/projects/ansible/main-ansible"
    accept_hostkey: true
  ignore_errors: true
