---
- name: Install aur packages
  tags:
    - aur
  kewlfft.aur.aur:
    name:
      - obsidian
      - dashbinsh
      - tmux-bash-completion-git
      - btrfs-assistant
      - btrfsmaintenance
    use: yay
    state: present
    update_cache: true
  when: ansible_distribution == "Archlinux"
  ignore_errors: true

- name: Install informant
  tags:
    - aur
  kewlfft.aur.aur:
    name:
      - informant
    use: yay
    state: present
    update_cache: false
  when: ansible_distribution == "Archlinux"
  ignore_errors: true
  register: install_informant

- name: Mark all informant news as read
  tags:
    - aur
  ansible.builtin.command: informant read --all
  become: true
  ignore_errors: true
  when: install_informant is changed
