---
- name: Install doas package
  tags:
    - doas
  ansible.builtin.package:
    name: doas
    state: present
    update_cache: false
  become: true

- name: Copy file doas.conf to /etc
  tags:
    - doas
  ansible.builtin.copy:
    src: doas.conf
    dest: /etc
    owner: root
    group: root
    mode: '0644'
  become: true
