---
- name: Neovim | Install treesitter support for python
  tags:
    - neovim
  ansible.builtin.command: nvim --headless +TSInstall python +qa

- name: Neovim | Install treesitter support for bash
  tags:
    - neovim
  ansible.builtin.command: nvim --headless +TSInstall bash +qa

- name: Neovim | Install treesitter support for json
  tags:
    - neovim
  ansible.builtin.command: nvim --headless +TSInstall json +qa

- name: Neovim | Install treesitter support for markdown
  tags:
    - neovim
  ansible.builtin.command: nvim --headless +TSInstall markdown +qa

- name: Neovim | Install treesitter support for yaml
  tags:
    - neovim
  ansible.builtin.command: nvim --headless +TSInstall yaml +qa

- name: Neovim | Install treesitter support for regex
  tags:
    - neovim
  ansible.builtin.command: nvim --headless +TSInstall regex +qa

- name: Neovim | Install treesitter support for html
  tags:
    - neovim
  ansible.builtin.command: nvim --headless +TSInstall html +qa

- name: Neovim | Install treesitter support for graphql
  tags:
    - neovim
  ansible.builtin.command: nvim --headless +TSInstall graphql +qa

- name: Neovim | Install treesitter support for docker
  tags:
    - neovim
  ansible.builtin.command: nvim --headless +TSInstall dockerfile +qa

- name: Neovim | Install treesitter support for css
  tags:
    - neovim
  ansible.builtin.command: nvim --headless +TSInstall css +qa

- name: Neovim | Install language servers packages
  tags:
    - neovim
  ansible.builtin.package:
    name:
      - pyright # python language server
      - bash-language-server # bash language server
    state: present
    update_cache: false
  become: true
  when: ansible_distribution == "Archlinux"

- name: Neovim | Install pyright (python language server via snap)
  tags:
    - neovim
  community.general.snap:
    name:
      - pyright
    state: present
    classic: true
  become: true
  when: ansible_distribution == "Ubuntu"

# - name: Neovim | Install sql-language-server and ansible-language-server package
# tags:
#    - neovim
# kewlfft.aur:
#   name:
#     - sqls-bin
#     - ansible-language-server
#     - terraform-ls
#   use: yay
#   state: present
#   update_cache: true
# when: ansible_distribution == "Archlinux"
# ignore_errors: true

# - name: Neovim | Install grammarly-languageserver and json language server
#   tags:
#     - neovim
#   community.general.npm:
#     name:
#       - unofficial-grammarly-language-server
#       - vscode-langservers-extracted
#     global: true
#     state: present
#   become: true

- name: Neovim | Install ansible-language-server when distribution in Ubuntu or Debian
  tags:
    - neovim
  community.general.npm:
    name: ansible-language-server
    global: true
    state: present
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Neovim | Create neovim directory for autoloading configurations
  tags:
    - neovim
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/autoload/"
    state: directory
    recurse: true
    mode: '0700'
    owner: "{{ lookup('env', 'USER') }}"

- name: Neovim | Copy sql-language-server file to .config
  tags:
    - neovim
  ansible.builtin.copy:
    src: sqllsrc.json
    dest: "{{ lookup('env', 'HOME') }}/.config/sql-language-server/"
    owner: "{{ lookup('env', 'USER') }}"
    mode: '0600'
