---
- name: Set packages variables when distribution is Archlinux (if necessary)
  tags:
    - packages
  ansible.builtin.set_fact:
    xorg:
      - xorg-server
      - xorg-xinit
      - xorg-xsetroot
      - xorg-xrandr
      - xorg-setxkbmap
      - xorg-xinput # Used on configure-trackball script
    rfkill: util-linux-libs
    python_pip: python-pip
    base_devel: base-devel
    wpa_supplicant: wpa_supplicant
    liberation_font: ttf-liberation
    postgres: postgresql-libs
    fd: fd
  when: ansible_distribution == "Archlinux"

- name: Set packages variable when distribution is Ubuntu (if necessary)
  tags:
    - packages
  ansible.builtin.set_fact:
    xorg:
      - xorg
      - libxrandr2
      - libxrandr-dev
      - xorg
      - xorg
      - xinput # Used on configure-trackball script
    rfkill: rfkill
    python_pip: pipenv
    base_devel: make
    wpa_supplicant: wpasupplicant
    liberation_font: fonts-liberation
    postgres: postgresql
    fd: fd-find
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: install packages and update cache
  tags:
    - packages
  ansible.builtin.package:
    name:
      - tmux
      - tmuxp
      - "{{ xorg[0] }}"
      - "{{ xorg[1] }}"
      - "{{ xorg[2] }}"
      - "{{ xorg[3] }}"
      - "{{ xorg[4] }}"
      - "{{ xorg[5] }}"
      - xautolock
      - xbindkeys
      - arandr
      - numlockx
      - "{{ python_pip }}"
      - feh
      - unclutter
      - "{{ base_devel }}"
      - xclip
      - brightnessctl
      - "{{ wpa_supplicant }}"
      - ripgrep
      - "{{ fd }}"
      - fzf
      - lxsession # polkit agent to fill password when launching applications with my run launcher
      - flameshot
      - bat
      - dunst
      - qt5ct # To set theme for qt applications
      - "{{ rfkill }}"
      - csvkit
      - yamllint
      - ansible-lint
      - npm # Necessary to install gramarly language server in neovim play
      - qutebrowser
      - unzip
      - "{{ liberation_font }}"
      - "{{ postgres }}"
      - mpv # Terminal based video player
      - yt-dlp # Download youtube videos, necessary to play youtube videos on mpv
      - plocate # Locate files faster than find
    state: present
    update_cache: true
  become: true

- name: install packages that i still have not set in ubuntu
  tags:
    - packages
  ansible.builtin.package:
    name:
      - pamixer # missing ubuntu
      - ttf-nerd-fonts-symbols-mono # missing ubuntu
      - ttf-nerd-fonts-symbols-common
      - ttf-nerd-fonts-symbols
      - ttf-joypixels # missing ubuntu
      - ttf-linux-libertine # missing ubuntu
      - arc-gtk-theme # missing ubuntu
      - clipmenu # missing ubuntu
      - noto-fonts-emoji # missing ubuntu
      - xcompmgr # Compositor to have transparency on the terminal
      - bleachbit # Utility to free space on disk
      - aws-cli
      - python-debugpy # Pythan debugger dependencie for nvim-dap-python
      - spotify-launcher
      - trash-cli
      - nethogs
      - man-db # Manpages
      - tldr # More concise man pages
      - git
      - zoxide # easily jump between directories using z + directory name
      - wol # provide Wake-on-Lan functionality
      - redshift # Adapt brightness and color of the screen at night
      - inetutils # Hostname command necessary for fish prompt
      - ntfs-3g # To mount drives formated as NTFS
      - zathura # Pdf reader
      - zathura-pdf-poppler # pdf reader
      - newsboat # RSS feed reader
      - python-adblock # To enable adblocking on qutebrowser
      - libreoffice-still # Office application
      - noto-fonts # Google Fonts
      - noto-fonts-extra # Aditional variants of google fonts
      - ncdu # Terminal disk space usage explorer utility
    state: present
    update_cache: true
  become: true
  when: ansible_distribution == "Archlinux"

- name: Refresh fonts
  tags:
    - packages
  ansible.builtin.shell: fc-cache
