---
- name: Clone st
  tags:
    - st
  ansible.builtin.git:
    version: main
    repo: git@github.com:andre-gonzalez/st.git
    dest: "{{ lookup('env', 'HOME') }}/.config/st"
    key_file: "{{ lookup('env', 'HOME') }}/.ssh/personal_id_ed25519_2023-11"
    accept_hostkey: true
  ignore_errors: true

- name: Install st
  tags:
    - st
  community.general.make:
    chdir: "{{ lookup('env', 'HOME') }}/.config/st"
    target: install
  become: true
