---
- name: Mysql | Install mysql package
  tags:
    - mysql
  kewlfft.aur.aur:
    name:
      - mysql
    use: yay
    state: present
    update_cache: true
  when: ansible_distribution == "Archlinux"
  ignore_errors: true
