---
- name: Packages | Install drawio
  tags:
    - packages
  ansible.builtin.package:
    name:
      - drawio-desktop
    state: present
    update_cache: true
  become: true

- name: Packages | Install claude-code
  tags:
    - aur
  kewlfft.aur.aur:
    name:
      - claude-code
    use: yay
    state: present
    update_cache: true
  when: ansible_facts["distribution"] == "Archlinux"
  ignore_errors: true
