---
- name: Terraform | Terraform archive-keyring.gpg download
  tags:
    - terraform
  ansible.builtin.get_url:
    url: terraform.gpg https://apt.releases.hashicorp.com/gpg
    dest: /usr/share/keyrings/terraform-archive-keyring.gpg
  become: true
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Terraform | Terraform PPA setting
  tags:
    - terraform
  ansible.builtin.shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/terraform-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" > /etc/apt/sources.list.d/terraform.list
  become: true
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Terraform | Terraform apt installation
  tags:
    - terraform
  ansible.builtin.package:
    name: terraform
    update_cache: true
  become: true
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Terraform | Install Terraform package
  tags:
    - terraform
  ansible.builtin.package:
    name:
      - terraform
    state: present
    update_cache: true
  become: true
  when: ansible_distribution == "Archlinux"

- name: Terraform | Install terraform language server
  tags:
    - terraform
  kewlfft.aur.aur:
    name:
      - terraform-ls
    use: yay
    state: present
    update_cache: true
  when: ansible_distribution == "Archlinux"
  ignore_errors: true

- name: Terraform | Install treesitter support for HCL (Terraform language)
  tags:
    - terraform
  ansible.builtin.command: nvim --headless +TSInstall hcl +qa
