---
- include_tasks: tasks/debug.yml
  tags:
    - debug
    - never
- include_tasks: tasks/ssh.yml
  tags:
    - full-install
    - light-install
    - ssh
- include_tasks: tasks/docker.yml
  tags:
    - docker
    - pihole
- include_tasks: tasks/pihole.yml
  tags:
    - pihole
