---
- include_tasks: tasks/debug.yml
  tags:
    - debug
    - never
- include_tasks: tasks/network-packages.yml
  tags:
    - network-packages
- include_tasks: tasks/ssh.yml
  tags:
    - ssh
- include_tasks: tasks/docker.yml
  tags:
    - docker
    - pihole
- include_tasks: tasks/pihole.yml
  tags:
    - pihole
