---
- name: Server | Include tasks from debug play
  ansible.builtin.include_tasks: tasks/debug.yml
  tags:
    - debug
    - never

- name: Server | Include tasks from Network Packages play
  ansible.builtin.include_tasks: tasks/network-packages.yml
  tags:
    - network-packages

- name: Server | Include tasks from ssh play
  ansible.builtin.include_tasks: tasks/ssh.yml
  tags:
    - ssh

- name: Server | Include tasks from docker play
  ansible.builtin.include_tasks: tasks/docker.yml
  tags:
    - docker
    - pihole

- name: Server | Include tasks from pihole play
  ansible.builtin.include_tasks: tasks/pihole.yml
  tags:
    - pihole
