---
- name: Network Packages | Install network managment packages
  tags:
    - network-packages
  ansible.builtin.package:
    name:
      - net-tools
      - iputils-ping
  become: true
  when: ansible_distribution in ["Debian", "Ubuntu"]
