---
- name: stop resolved service
  tags:
    - pihole
  ansible.builtin.service:
    name: systemd-resolved
    state: stopped
    enabled: false
  become: true

- name: Change /etc/resolv.conf nameserver to cloudflare DNS
  tags:
    - pihole
  ansible.builtin.lineinfile:
    path: /etc/resolv.conf
    regexp: '.*nameserver.*'
    line: 'nameserver 1.1.1.2'
    backrefs: true
  become: true

- name: Pull pihole docker image
  tags:
    - docker
    - pihole
  community.docker.docker_image:
    name: pihole/pihole
    source: pull
    pull:
      platform: amd64
  become: true

- name: Allow ports 80, 53 and 67 on ufw for pihole
  tags:
    - pihole
  community.general.ufw:
    rule: allow
    port: '{{ item.port }}'
    proto: '{{ item.proto }}'
  loop:
    - { port: '80', proto: 'tcp' }
    - { port: '53', proto: 'tcp' }
    - { port: '53', proto: 'udp' }
    - { port: '67', proto: 'tcp' }
    - { port: '67', proto: 'udp' }
  become: true

- name: Ensure pihole directory exists.
  tags:
    - pihole
  ansible.builtin.file:
    dest: "{{ lookup('env', 'HOME') }}/pihole/"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: 0740
    state: directory

- name: copy pihole docker compose file
  tags:
    - pihole
  ansible.builtin.copy:
    src: pihole-docker-compose
    dest: "{{ lookup('env', 'HOME') }}/pihole/docker-compose.yml"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: 0640

- name: Deploy Docker Compose pihole
  tags:
    - pihole
  community.docker.docker_compose:
    project_src: "{{ lookup('env', 'HOME') }}/pihole"
    files: docker-compose.yml
  become: true
