---
- name: Process Accounting | Install acct package
  tags:
    - process-accounting
  ansible.builtin.package:
    name: acct
    state: present
  become: true
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Process Accounting | Enable and strat acct process
  tags:
    - process-accounting
  ansible.builtin.service:
    name: acct
    state: started
    enabled: true
  become: true
