---
- name: SSH | Start sshd
  tags:
    - ssh
  ansible.builtin.service:
    name: sshd
    state: started
    enabled: true
  become: true

- name: SSH | Install cron job (stop ssh at night)
  tags:
    - ssh
  ansible.builtin.cron:
    user: root
    name: stop ssh at night
    hour: "0"
    disabled: false
    job: systemctl stop sshd
  become: true

- name: SSH | Install cron job (Start ssh at morning)
  tags:
    - ssh
  ansible.builtin.cron:
    user: root
    name: Start ssh at morning
    hour: "5"
    disabled: false
    job: systemctl start sshd
  become: true

- name: SSH | Disable Compression on ssh to increase security
  tags:
    - ssh
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^(#)Compression
    line: Compression no
    state: present
    backup: true
  become: true
  notify: Restart ssh
