---
- name: Drives | Ensure /mnt/hd-interno directory exists.
  tags:
    - drives
  ansible.builtin.file:
    dest: /mnt/hd-interno
    mode: '0770'
    state: directory

- name: Drives | Mount internal hard-drive
  tags:
    - drives
  ansible.builtin.lineinfile:
    path: /etc/fstab
    state: present
    line: '{{ item.line }}'
  loop:
    - { line: '# /dev/sda2' }
    - { line: 'PARTUUID=72749a9f-5496-4700-ad5e-f4f2eaad8da5 /mnt/hd-interno ext4    defaults        0       0' }
  become: true

- name: Drives | Ensure /mnt/ntfs-hd-interno directory exists.
  tags:
    - drives
  ansible.builtin.file:
    dest: /mnt/ntfs-hd-interno
    mode: '0770'
    state: directory

- name: Drives | Mount internal hard-drive
  tags:
    - drives
  ansible.builtin.lineinfile:
    path: /etc/fstab
    state: present
    line: '{{ item.line }}'
  loop:
    - { line: '# /dev/sda1' }
    - { line: 'PARTUUID=f41cf00e-dbf1-431f-a833-9f9e20ebed89 /mnt/ntfs-hd-interno ntfs    defaults        0       0' }
  become: true
