---
- name: Samsung Expert | Include tasks from drives play
  ansible.builtin.include_tasks: tasks/drives.yml
  tags:
    - drives

- name: Samsung Expert | Include tasks from network play
  ansible.builtin.include_tasks: tasks/network.yml
  tags:
    - network

- name: Samsung Expert | Include tasks from nvidia play
  ansible.builtin.include_tasks: tasks/nvidia.yml
  tags:
    - nvidia
