---
- name: Install wireless drivers (samsung_expert)
  tags:
    - network
  ansible.builtin.package:
    name:
      - broadcom-wl
    state: present
    update_cache: false
  when: ansible_distribution in ["Archlinux"]
  become: true
  register: restart_network

- name: Restart systemd-networkd
  tags:
    - network
  ansible.builtin.service:
    name: systemd-networkd
    state: restarted
    enabled: true
  become: true
  when: restart_network is changed

- name: Start iwd
  tags:
    - network
  ansible.builtin.service:
    name: iwd
    state: restarted
    enabled: true
  become: true
  when: restart_network is changed
