---
- name: Install wireless drivers (samsung_expert)
  tags:
    - network
  ansible.builtin.package:
    name:
      - broadcom-wl
    state: present
    update_cache: false
  when: ansible_distribution in ["Archlinux"]
  become: true
  # notify: restart_network
