---
- name: Docker | Install docker
  tags:
    - docker
    - pihole
  ansible.builtin.package:
    name:
      - docker-compose
  become: true

- name: Docker | Start docker
  tags:
    - docker
    - pihole
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  become: true

- name: Docker | Add to the docker group the user {{ lookup('env', 'USER') }}
  tags:
    - docker
    - pihole
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    groups: docker
    append: true
  become: true
