---
- name: Cron | Set cron variable when distribution is Archlinux
  tags:
    - cron
  ansible.builtin.set_fact:
    cron: cronie
  when: ansible_distribution == "Archlinux"

- name: Cron | Set cron variable when distribution is Ubuntu on Debian
  tags:
    - cron
  ansible.builtin.set_fact:
    cron: cron
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Cron | Install cron
  tags:
    - cron
  ansible.builtin.package:
    name: "{{ cron }}"
    state: present
    update_cache: false
  become: true

- name: Cron | Start cron
  tags:
    - cron
  ansible.builtin.service:
    name: "{{ cron }}"
    state: started
    enabled: true
  become: true
