---
- name: Locale | Install locale package when distribution is Ubuntu
  tags:
    - locale
  ansible.builtin.package:
    name:
      - locales
    state: present
  become: true
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Locale | Set timezone to "{{ timezone }}"
  tags:
    - timezone
  community.general.timezone:
    name: "{{ timezone }}"
  become: true

- name: Locale | Ensure the locale exists
  tags:
    - locale
  community.general.locale_gen:
    name: "{{ locale }}"
    state: present
  become: true
