---
- name: Security | Disable root login
  tags:
    - security
  ansible.builtin.user:
    name: root
    shell: /sbin/nologin
  become: true

- name: Security | Install fail2ban
  tags:
    - security
    - fail2ban
  ansible.builtin.package:
    name: fail2ban
  become: true
  notify: start fail2ban

- name: Security | Ensure /etc/fail2ban directory exists
  tags:
    - security
    - fail2ban
  ansible.builtin.file:
    dest: /etc/fail2ban
    group: root
    mode: "1755"
    state: directory
  become: true

- name: Security | Copy fail2ban configuration file
  tags:
    - security
    - fail2ban
  ansible.builtin.copy:
    src: jail.local
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: start fail2ban

- name: Security | Install apparmor on Archlinux
  tags:
    - security
    - apparmor
  ansible.builtin.package:
    name:
      - apparmor
      - audit
      - python-notify2
  become: true
  when: ansible_distribution == "Archlinux"
  notify: start apparmor

- name: Security | Install apparmor on Ubuntu or Debian
  tags:
    - security
    - apparmor
  ansible.builtin.package:
    name:
      - apparmor
      - apparmor-utils
      - apparmor-profiles-extra
      - apparmor-profiles
  become: true
  when: ansible_distribution in ["Ubuntu", "Debian"]
  notify: start apparmor

- name: Security | Enable apparmor in kernel parameters with audit enabled on Archlinux
  tags:
    - grub
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: .*GRUB_CMDLINE_LINUX_DEFAULT=.*
    line: GRUB_CMDLINE_LINUX_DEFAULT="loglevel=3 quiet lsm=landlock,lockdown,yama,integrity,apparmor,bpf" audit=1
    backrefs: true
  become: true
  when: ansible_distribution == "Archlinux" and ansible_service_mgr == "grub"
  notify: update grub

- name: Security | Ensure grub.d directory exists on Debian and Ubuntu
  tags:
    - ssh
  ansible.builtin.file:
    dest: /etc/default/grub.d
    mode: "0700"
    state: directory
    recurse: true
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Security | Ensure apparmor.cfg file exists on Debian and Ubuntu
  tags:
    - ssh
  ansible.builtin.file:
    dest: /etc/default/grub.d/apparmor.cfg
    mode: "0700"
    state: touch
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Security | Enable apparmor in kernel parameters with audit enabled on Debian and ubuntu
  tags:
    - security
    - apparmor
  ansible.builtin.lineinfile:
    path: /etc/default/grub.d/apparmor.cfg
    line: GRUB_CMDLINE_LINUX_DEFAULT="$GRUB_CMDLINE_LINUX_DEFAULT apparmor=1 security=apparmor"
  become: true
  when: ansible_distribution in ["Ubuntu", "Debian"] and ansible_service_mgr == "grub"
  notify: update grub

- name: Security | Install auditd package
  tags:
    - security
    - apparmor
  ansible.builtin.package:
    name: auditd
  become: true
  when: ansible_distribution in ["Ubuntu", "Debian"]
  notify: Restart auditd

- name: Security | Ensure group audit exists
  tags:
    - security
    - apparmor
  ansible.builtin.group:
    name: audit
    state: present
  become: true

- name: Security | Add to group audit the user {{ lookup('env', 'USER') }}
  tags:
    - security
    - apparmor
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    groups: audit
    append: true
  become: true

- name: Security | Add audit group to auditd.conf
  tags:
    - security
    - apparmor
  ansible.builtin.lineinfile:
    path: /etc/audit/auditd.conf
    line: log_group = audit
  become: true

- name: Security | Ensure autostart directory exists.
  tags:
    - pihole
  ansible.builtin.file:
    dest: "{{ lookup('env', 'HOME') }}/.config/autostart/"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: "0644"
    state: directory

- name: Security | Copy apparmor-notify.desktop file to autostart apparmor notify
  tags:
    - security
    - apparmor
  ansible.builtin.copy:
    src: apparmor-notify.desktop
    dest: "{{ lookup('env', 'HOME') }}/.config/autostart"
    owner: "{{ lookup('env', 'USER') }}"
    group: audit
    mode: "0644"
  become: true

- name: Security | Enable write-cache to speed up apparmor
  tags:
    - security
    - apparmor
  ansible.builtin.lineinfile:
    path: /etc/apparmor/parser.conf
    regexp: "#write-cache"
    line: write-cache
    backrefs: true
  become: true

- name: Security | Install security updates automatically
  tags:
    - security
  ansible.builtin.package:
    name: unattended-upgrades
  become: true
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Security | Install apt-listbugs to check if upgrades are safe on Debian and Ubuntu
  tags:
    - security
  ansible.builtin.package:
    name: apt-listbugs
  become: true
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Security | Install libpam-tmpdir to improve security on tmp files
  tags:
    - security
  ansible.builtin.package:
    name: libpam-tmpdir
  become: true
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Security | Install debsums to improve security verifying packages with known good database
  tags:
    - security
  ansible.builtin.package:
    name: debsums
  become: true
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Security | Install apt-show-versions for patch managment
  tags:
    - security
  ansible.builtin.package:
    name: apt-show-versions
  become: true
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Security | Install rkhunter as malware scanning tool
  tags:
    - security
  ansible.builtin.package:
    name:
      - rkhunter
  become: true

- name: Security | Install chkrootkit as malware scanning tools
  tags:
    - security
  ansible.builtin.package:
    name:
      - chkrootkit
  become: true
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Security | Add legal banners
  tags:
    - security
  ansible.builtin.lineinfile:
    path: "{{ item.path }}"
    line: Unauthorized access is prohibited. All activity is monitored.
    mode: "0644"
    create: true
  loop:
    - {path: /etc/issue }
    - {path: /etc/issue.net }
  become: true

- name: SSH | Add legal banner to ssh
  tags:
    - security
    - ssh
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^(#)Banner.*
    line: Banner /etc/issue.net
    state: present
    backup: true
  become: true
  notify: restart ssh

- name: Security | Disable core dumps
  tags:
    - security
  ansible.builtin.lineinfile:
    path: /etc/security/limits.conf
    line: "* hard core 0"
    mode: "0644"
    create: true
  become: true

- name: Security | Configure Password Hashing Rounds to a minimum of 5000
  tags:
    - security
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: ^(#)SHA_CRYPT_MIN_ROUNDS
    line: SHA_CRYPT_MIN_ROUNDS 5000
    mode: "0644"
    create: true
  become: true

- name: Security | Install libpam-passwdqc package to check passwords
  tags:
    - security
  ansible.builtin.package:
    name: libpam-passwdqc
  become: true
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Security | Install aide to monitor file changes
  tags:
    - security
  ansible.builtin.package:
    name: aide
  become: true
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Security | Configure password strength testing
  tags:
    - security
  ansible.builtin.lineinfile:
    path: /etc/pam.d/common-password
    line: password requisite pam_passwdqc.so min=8,7,6,4,4 max=40 passphrase=3 similar=deny
    mode: "0644"
    create: true
  become: true
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Security | Set maximum number of days a password can be used to 180
  tags:
    - security
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: ^PASS_MAX_DAYS\t\d*$
    line: PASS_MAX_DAYS   180
    mode: "0644"
    create: true
  become: true

- name: Security | Set password warning to begin 30 days before expiration date
  tags:
    - security
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: ^PASS_WARN_AGE\t\d*$
    line: PASS_WARN_AGE   30
    mode: "0644"
    create: true
  become: true

- name: Security | Set minimum password days to 1
  tags:
    - security
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: ^PASS_MIN_DAYS\t\d*$
    line: PASS_MIN_DAYS   1
    mode: "0644"
    create: true
  become: true
