---
- name: Install openssh
  tags:
    - full-install
    - light-install
    - ssh
  ansible.builtin.package:
    name: openssh
    state: present
    update_cache: true
  when: ansible_distribution == "Archlinux"
  become: true

- name: Ensure .ssh directory exists.
  tags:
    - full-install
    - light-install
    - ssh
  ansible.builtin.file:
    dest: "{{ ansible_env.HOME }}/.ssh"
    mode: 0700
    state: directory

- name: Install ssh key public
  tags:
    - full-install
    - light-install
    - ssh
  ansible.builtin.copy:
    src: id_rsa.pub
    dest: "{{ ansible_env.HOME }}/.ssh"
    mode: 0644
  notify: "secure ssh"

- name: add ssh key for frank
  tags:
    - full-install
    - light-install
    - ssh
  ansible.posix.authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  notify: "secure ssh"
