---
- name: SSH | Set ssh variable when distribution is Archlinux
  tags:
    - ssh
  ansible.builtin.set_fact:
    ssh_package: openssh
  when: ansible_distribution == "Archlinux"

- name: SSH | Set intel variable when distribution is Ubuntu or Debian
  tags:
    - ssh
  ansible.builtin.set_fact:
    ssh_package: openssh-server
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: SSH | Install openssh
  tags:
    - ssh
  ansible.builtin.package:
    name: "{{ ssh_package }}"
    state: present
    update_cache: true
  become: true

- name: SSH | Ensure .ssh directory exists.
  tags:
    - ssh
  ansible.builtin.file:
    dest: "{{ lookup('env', 'HOME') }}/.ssh"
    mode: '0700'
    state: directory

- name: SSH | Set authorized keys from github to user {{ lookup('env', 'USER') }}
  tags:
    - ssh
  ansible.posix.authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('url', 'https://github.com/andre-gonzalez.keys', split_lines=False) }}"
  notify: "restart ssh"

- name: SSH | Change ssh port
  tags:
    - ssh
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '#Port .*'
    line: 'Port {{ ssh_port }}'
    backrefs: true
  become: true
  notify: "restart ssh"

- name: SSH | Disable root login via ssh
  tags:
    - security
    - ssh
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^(#)PermitRootLogin .*'
    line: "PermitRootLogin no"
    state: present
    backup: true
  become: true
  notify: "restart ssh"

- name: SSH | Disable password login via ssh
  tags:
    - security
    - ssh
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^(#)PasswordAuthentication .*'
    line: "PasswordAuthentication no"
    state: present
    backup: true
  become: true
  notify: "restart ssh"

- name: SSH | Only allow user {{ lookup('env', 'USER') }}
  tags:
    - security
    - ssh
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^AllowUsers'
    line: "AllowUsers {{ lookup('env', 'USER') }}"
    state: present
    backup: true
  become: true
  notify: "restart ssh"

- name: SSH | Do not permit empty passwords on ssh
  tags:
    - security
    - ssh
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^(#)PermitEmptyPasswords'
    line: "PermitEmptyPasswords no"
    state: present
    backup: true
  become: true
  notify: "restart ssh"

- name: SSH | Limit max auth tries to 6
  tags:
    - security
    - ssh
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^(#)MaxAuthTries'
    line: "MaxAuthTries 6"
    state: present
    backup: true
  become: true
  notify: "restart ssh"

- name: SSH | Block X11Forwarding on ssh
  tags:
    - security
    - ssh
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^(#)X11Forwarding .*'
    line: "X11Forwarding no"
    state: present
    backup: true
  become: true
  notify: "restart ssh"

- name: SSH | Block TCP Forwarding on ssh
  tags:
    - security
    - ssh
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^(#)AllowTcpForwarding'
    line: "AllowTcpForwarding no"
    state: present
    backup: true
  become: true
  notify: "restart ssh"
