---
- name: Install openssh
  tags:
    - full-install
    - light-install
    - ssh
  ansible.builtin.package:
    name: openssh
    state: present
    update_cache: true
  when: ansible_distribution == "Archlinux"
  become: true

- name: Ensure .ssh directory exists.
  tags:
    - full-install
    - light-install
    - ssh
  ansible.builtin.file:
    dest: "{{ lookup('env', 'HOME') }}/.ssh"
    mode: 0700
    state: directory

- name: add ssh key for  "{{ lookup('env', 'USER') }}"
  tags:
    - full-install
    - light-install
    - ssh
  ansible.posix.authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  notify: "restart ssh"

- name: Change ssh port
  tags:
    - full-install
    - light-install
    - ssh
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '#Port .*'
    line: 'Port {{ ssh_port }}'
    backrefs: true
  become: true
  notify: "restart ssh"

- name: Disable root login via ssh
  tags:
    - full-install
    - light-install
    - security
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: "PermitRootLogin no"
    state: present
    backup: true
  become: true
  notify: "restart ssh"

- name: Disable password login via ssh
  tags:
    - full-install
    - light-install
    - security
    - ssh
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: "PasswordAuthentication no"
    state: present
    backup: true
  become: true
  notify: "restart ssh"
