---
- name: Set ssh variable when distribution is Archlinux
  tags:
    - full-install
    - light-install
    - ssh
  ansible.builtin.set_fact:
    ssh_package: openssh
  when: ansible_distribution == "Archlinux"

- name: Set intel variable when distribution is Ubuntu or Debian
  tags:
    - full-install
    - light-install
    - ssh
  ansible.builtin.set_fact:
    ssh_package: openssh-server
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Install openssh
  tags:
    - full-install
    - light-install
    - ssh
  ansible.builtin.package:
    name: "{{ ssh_package }}"
    state: present
    update_cache: true
  become: true

- name: Ensure .ssh directory exists.
  tags:
    - full-install
    - light-install
    - ssh
  ansible.builtin.file:
    dest: "{{ lookup('env', 'HOME') }}/.ssh"
    mode: 0700
    state: directory

- name: Set authorized keys for {{ lookup('env', 'USER') }} from github
  tags:
    - full-install
    - light-install
    - ssh
  ansible.posix.authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('url', 'https://github.com/andre-gonzalez.keys', split_lines=False) }}"
  notify: "restart ssh"

- name: Change ssh port
  tags:
    - full-install
    - light-install
    - ssh
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '#Port .*'
    line: 'Port {{ ssh_port }}'
    backrefs: true
  become: true
  notify: "restart ssh"

- name: Disable root login via ssh
  tags:
    - full-install
    - light-install
    - security
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: "PermitRootLogin no"
    state: present
    backup: true
  become: true
  notify: "restart ssh"

- name: Disable password login via ssh
  tags:
    - full-install
    - light-install
    - security
    - ssh
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: "PasswordAuthentication no"
    state: present
    backup: true
  become: true
  notify: "restart ssh"
