---
- name: tailscale-debian | Tailscale | Apt Dependencies
  become: true
  ansible.builtin.apt:
    name: "{{ base_tailscale_apt_dependencies }}"
    cache_valid_time: 3600
    state: present

- name: tailscale-debian | Tailscale | Legacy Apt Dependencies
  become: true
  ansible.builtin.apt:
    name: "{{ base_tailscale_legacy_apt_dependencies }}"
  when:
    - ansible_facts["distribution_major_version"] | int < 11
    # Prelease versions of debian tend to not have a version integer yet
    - ansible_facts["distribution_major_version"] != "testing"
    - ansible_facts["distribution_major_version"] != "n/a"

- name: tailscale-debian | Tailscale | Add Tailscale Signing Key
  become: true
  ansible.builtin.get_url:
    url: "{{ base_tailscale_apt_signkey }}"
    dest: "{{ base_tailscale_apt_keyring_path }}"
    mode: "0644"

- name: tailscale-debian | Tailscale | Add Tailscale Deb
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ base_tailscale_apt_deb }}"
    state: present

- name: tailscale-debian | Tailscale | Install Tailscale
  become: true
  ansible.builtin.apt:
    name: "{{ base_tailscale_package }}"
    cache_valid_time: 3600
    state: "{{ base_tailscale_state }}"
