---
- name: tailscale-arch | Tailscale | Install Tailscale
  become: true
  community.general.pacman:
    name: "{{ base_tailscale_package }}"
    update_cache: true
    state: "{{ base_tailscale_state }}"
