---
- name: Users | Create frank group
  tags:
    - users
  ansible.builtin.group:
    name: frank
    state: present

- name: Users | Create ansible group
  tags:
    - users
  ansible.builtin.group:
    name: ansible
    state: present

- name: Users | Set fact for Debian
  tags:
    - users
  ansible.builtin.set_fact:
    base_sudo_group: sudo
  when: ansible_os_family == "Debian"

- name: Users | Set fact for ArchLinux
  tags:
    - users
  ansible.builtin.set_fact:
    base_sudo_group: wheel
  when: ansible_os_family == "Archlinux"

- name: Users | Create user {{ lookup('env', 'USER') }}
  tags:
    - users
  ansible.builtin.user:
    name: frank
    group: frank
    groups: adm,{{ base_sudo_group }}
    state: present

- name: Users | Create ansible user
  tags:
    - users
    - ansible
  ansible.builtin.user:
    name: ansible
    system: true
  become: true

- name: Users | Copy sudoers_ansible
  tags:
    - users
    - ansible
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: sudoers_ansible, dest: /etc/sudoers.d/ansible, mode: "0440" }
    - { src: sudoers_frank, dest: /etc/sudoers.d/frank, mode: "0440" }
  become: true
