---
- name: Anki | Ensure anki directory exists
  tags:
    - anki
  ansible.builtin.file:
    dest: "{{ lookup('env', 'HOME') }}/.config/anki/install-files"
    mode: "0700"
    state: directory

- name: Anki | Get latest anki release
  tags:
    - anki
  ansible.builtin.uri:
    url: https://api.github.com/repos/ankitects/anki/releases/latest
    return_content: true
  register: json_reponse

- name: Anki | Download anki installer
  tags:
    - anki
  ansible.builtin.get_url:
    url: "{{ json_reponse.json.assets.2.browser_download_url }}"
    dest: "{{ lookup('env', 'HOME') }}/.config/anki/anki-installer.tar.zst"
    force: true
    mode: "0777"
  notify: proceed_anki_installation
