---
# - name: Audio | Install pulseaudio packages
#   tags:
#     - pulseaudio
#   ansible.builtin.package:
#     name:
#       - pulseaudio
#       - alsa-utils
#       - pavucontrol
#       - pulseaudio-bluetooth
#       - pulseaudio-alsa
#     state: present
#   become: true
#   register: restart_pulseaudio

# - name: Audio | Set pulseaudio to automatically change to the bluetooth once connected
#   tags:
#     - pulseaudio
#   ansible.builtin.lineinfile:
#     path: /etc/pulse/default.pa
#     line: 'load-module module-switch-on-connect'
#     create: yes
#     backrefs: true
#     state: present
#   become: true

# - name: Audio | Restart pulseaudio
#   tags:
#     - pulseaudio
#   ansible.builtin.service:
#     name: pulseaudio
#     state: restarted
#     enabled: true
#   become: true
#   when: restart_pulseaudio is changed

- name: Audio | Install pipewire packages on Arch
  tags:
    - pipewire
  ansible.builtin.package:
    name:
      - alsa-utils
      - pavucontrol # Audio control interface
      - pipewire-alsa # Rounte all application using ALSA API through pipewire
      - pipewire-docs # Not necessary. Only documentation
      - wireplumber # Session manager. Alternative to pipewire-media-session
      - qpwgraph # GUI session manager
      - pipewire-pulse
      - pipewire-jack
      - pipewire-audio
      - pipewire
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: Audio | Install pipewire packages on Debian
  tags:
    - pipewire
  ansible.builtin.package:
    name:
      - pipewire
      - pipewire-audio-client-libraries
    state: present
  become: true
  when: ansible_distribution == "Debian"
