---
- name: AUR | Install aur packages
  tags:
    - aur
  kewlfft.aur.aur:
    name:
      - obsidian
      - dashbinsh
      - tmux-bash-completion-git
      - btrfs-assistant
      - btrfsmaintenance
      - yewtube # Search youtube videos from the terminal
    use: yay
    state: present
    update_cache: true
  when: ansible_distribution == "Archlinux"
  ignore_errors: true

- name: AUR | Install informant
  tags:
    - aur
  kewlfft.aur.aur:
    name:
      - informant
    use: yay
    state: present
    update_cache: false
  when: ansible_distribution == "Archlinux"
  ignore_errors: true
  notify: install_informant
