---
- name: AUR | Install aur packages
  tags:
    - aur
  kewlfft.aur.aur:
    name:
      - obsidian
      - dashbinsh
      - tmux-bash-completion-git
      - btrfs-assistant
      - btrfsmaintenance
      - yewtube # Search youtube videos from the terminal
      - sent-git # Simple plain-text presentation tool
      - farbfeld # Image viewer that i use with sent
      - aur-auto-vote-git # Package to auto vote on AUR packages
      - zen-browser-bin # Zen browser optimized for newer CPUs
      - thorium-browser-bin
      - advcpmv # Add progress bar to cp and mv commands
      - megasync-bin # Mega drive sync program
      - xautolock
      - advcpmv # Cp and mv commands that shows progress
      - arc-gtk-theme # Set theme for gtk apps
      - ttf-joypixels
      - checkupdates-with-aur
    use: yay
    state: present
    update_cache: true
  when: ansible_distribution == "Archlinux"
  ignore_errors: true

- name: AUR | Install informant
  tags:
    - aur
  kewlfft.aur.aur:
    name:
      - informant
    use: yay
    state: present
    update_cache: false
  when: ansible_distribution == "Archlinux"
  ignore_errors: true
  notify: install_informant
