---
- name: Autorandr | Install autorandr
  tags:
    - autorandr
  ansible.builtin.package:
    name: autorandr
  become: true

- name: Autorandr | Ensure autorandr config directory exists
  tags:
    - autorandr
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.config/autorandr"
    state: directory
    mode: '0755'

- name: Autorandr | Copy autorandr profiles
  tags:
    - autorandr
  ansible.builtin.copy:
    src: "files/autorandr/"
    dest: "{{ lookup('env', 'HOME') }}/.config/autorandr/"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: '0644'

- name: Autorandr | Ensure .xinitrc file exists in home directory
  tags:
    - autorandr
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.xinitrc"
    state: touch
    mode: '0644'

- name: Autorandr | Ensure autorandr is called on X startup
  tags:
    - autorandr
  ansible.builtin.lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.xinitrc"
    line: "autorandr --change"
    state: present

- name: Autorandr | Deploy udev rule for monitor hotplug
  tags:
    - autorandr
  ansible.builtin.copy:
    dest: /etc/udev/rules.d/40-monitor-hotplug.rules
    content: |
      ACTION=="change", SUBSYSTEM=="drm", RUN+="/usr/bin/autorandr --change"
    owner: root
    group: root
    mode: '0644'
  become: true
  register: update_udev

- name: Autorandr | Reload udev rules
  tags:
    - autorandr
  ansible.builtin.command: udevadm control --reload-rules
  become: true
  when: update_udev is changed
