---
- name: Cron | Install cron job (ansible-pull)
  tags:
    - cron
  ansible.builtin.cron:
    user: ansible
    name: ansible provision
    minute: "*/10"
    disabled: true
    job: /usr/bin/ansible-pull --vault-password-file {{ lookup('env', 'HOME') }}/.vault_key -o -U https://github.com/andre-gonzalez/ansible-pull.git 2>> {{ lookup('env',
      'HOME') }}/.cron-errors/ansible-pull-error-logs.txt 1>> {{ lookup('env', 'HOME') }}/.cron-errors//gdrive-pessoal/pessoal/programação/cron-logs/stdout-logs/ansible-pull-stdout-logs.txt
  become: true

- name: Cron | Install cron job (profile-selector)
  tags:
    - cron
  ansible.builtin.cron:
    user: "{{ lookup('env', 'USER') }}"
    name: profile-selector
    special_time: reboot
    disabled: false
    job: DISPLAY=:0 {{ lookup('env', 'HOME') }}/.scripts/profile-selector
  become: true

- name: Cron | Install cron job (remove downloads folder)
  tags:
    - cron
  ansible.builtin.cron:
    user: "{{ lookup('env', 'USER') }}"
    name: remove-downloads-folder-reboot
    special_time: reboot
    disabled: false
    job: sleep 60 && rm -r {{ lookup('env', 'HOME') }}/Downloads

- name: Cron | Install cron job (remove downloads folder)
  tags:
    - cron
  ansible.builtin.cron:
    user: "{{ lookup('env', 'USER') }}"
    name: remove-downloads-folder
    minute: "*/10"
    disabled: false
    job: rm -r {{ lookup('env', 'HOME') }}/Downloads

- name: Cron | Install cron job (push notes to git repository)
  tags:
    - cron
  ansible.builtin.cron:
    user: "{{ lookup('env', 'USER') }}"
    name: push notes to git repository
    minute: "*/10"
    disabled: false
    job: /bin/sh {{ lookup('env', 'HOME') }}/.scripts/push-new-notes.sh 2>> {{ lookup('env', 'HOME') }}/.cron-errors/push-new-notes-error-logs.txt 1>> {{ lookup('env',
      'HOME') }}/gdrive-pessoal/pessoal/programação/cron-logs/stdout-logs/push-new-notes-stdout-logs.txt

- name: Cron | Install cron job (Auto adjust screen brightness)
  tags:
    - cron
    - auto-adjust-brightness
  ansible.builtin.cron:
    user: root
    name: Auto adjust screen brightness
    minute: "*/5"
    hour: 17-19,6-15
    disabled: false
    job: /bin/sh {{ lookup('env', 'HOME') }}/.scripts/auto-adjust-brightness.sh 2>> {{ lookup('env', 'HOME') }}/.cron-errors/auto-adjust-brightness-error-logs.txt
      1>> {{ lookup('env', 'HOME') }}/gdrive-pessoal/pessoal/programação/cron-logs/stdout-logs/auto-adjust-brightness-stdout-logs.txt
  become: true
  when: '"Notebook" in ansible_facts["form_factor"]'
