---
- name: Directories | Ensure gdrive-pessoal, not-up and iso directories exists.
  tags:
    - directories
  ansible.builtin.file:
    dest: "{{ lookup('env', 'HOME') }}/gdrive-pessoal/not-up/iso"
    mode: "0770"
    group: "{{ lookup('env', 'USER') }}"
    owner: "{{ lookup('env', 'USER') }}"
    state: directory

- name: Directories | Ensure projects directory exists.
  tags:
    - directories
  ansible.builtin.file:
    dest: "{{ lookup('env', 'HOME') }}/projects/"
    mode: "0770"
    group: "{{ lookup('env', 'USER') }}"
    owner: "{{ lookup('env', 'USER') }}"
    state: directory

- name: Directories | Ensure /mnt/hd-externo directory exists.
  tags:
    - directories
  ansible.builtin.file:
    dest: "{{ item.dest }}"
    mode: "0770"
    state: directory
  loop:
    - { dest: /mnt/hd-externo }
    - { dest: /mnt/ntfs-hd-externo }
    - { dest: /mnt/hd-interno }
    - { dest: /mnt/ntfs-hd-interno }
  become: true
