---
- name: Dotfiles | Cloning .dotfiles
  tags:
    - dotfiles
  ansible.builtin.git:
    version: main
    repo: git@github.com:andre-gonzalez/dotfiles.git
    dest: "{{ lookup('env', 'HOME') }}/.config/dotfiles"
    recursive: true
    update: true
    bare: true
    accept_hostkey: true
    key_file: "{{ lookup('env', 'HOME') }}/.ssh/personal_id_ed25519_2023-11"
  register: dotfiles_repo

- name: Dotfiles | Set up dotfiles
  tags:
    - dotfiles
  ansible.builtin.command: /usr/bin/git --git-dir={{ lookup('env', 'HOME') }}/.config/dotfiles/ --work-tree={{ lookup('env', 'HOME') }} checkout -f
  when: dotfiles_repo is changed
