---
- name: Dotfiles | Cloning .dotfiles
  tags:
    - dotfiles
  ansible.builtin.git:
    version: main
    repo: git@github.com:andre-gonzalez/dotfiles.git
    dest: "{{ lookup('env', 'HOME') }}/.config/dotfiles"
    recursive: true
    update: true
    bare: true
    accept_hostkey: true
    key_file: "{{ lookup('env', 'HOME') }}/.ssh/personal_id_ed25519_2023-11"
  notify: set_up_dotfiles
