---
- name: DWM | Install gcc, libxft-dev, libxinerama-dev (dwm dependency)
  tags:
    - dwm
  ansible.builtin.package:
    name:
      - gcc
      - libxft-dev
      - libxinerama-dev
      - xwininfo # Necessary for my profile selector script
      - ttf-dejavu # Font I choosed in my config
    state: present
    update_cache: true
  become: true
  when: ansible_distribution == "Ubuntu"

- name: DWM | Clone dwm (Laptop)
  tags:
    - dwm
  ansible.builtin.git:
    version: main
    repo: git@github.com:andre-gonzalez/dwm.git
    dest: "{{ lookup('env', 'HOME') }}/.config/dwm/laptop-dwm/"
    key_file: "{{ lookup('env', 'HOME') }}/.ssh/personal_id_ed25519_2023-11"
    accept_hostkey: true
  ignore_errors: true

- name: DWM | Clone dwm (Ultra wide screen)
  tags:
    - dwm
  ansible.builtin.git:
    version: ultra-wide-dwm
    repo: git@github.com:andre-gonzalez/dwm.git
    dest: "{{ lookup('env', 'HOME') }}/.config/dwm/ultra-wide-dwm/"
    key_file: "{{ lookup('env', 'HOME') }}/.ssh/personal_id_ed25519_2023-11"
    accept_hostkey: true
  ignore_errors: true

- name: DWM | Install dwm (laptop)
  tags:
    - dwm
  community.general.make:
    chdir: "{{ lookup('env', 'HOME') }}/.config/dwm/laptop-dwm/"
    target: install
  become: true
  when: '"Notebook" in ansible_facts["form_factor"]'

- name: DWM | Install dwm (ultra-wide)
  tags:
    - dwm
  community.general.make:
    chdir: "{{ lookup('env', 'HOME') }}/.config/dwm/ultra-wide-dwm/"
    target: install
  become: true
  when: '"Notebook" not in ansible_facts["form_factor"]'
