---
# - name: Grub | Copy file grub config file
#   tags:
#     - grub
#   ansible.builtin.copy:
#     src: grub
#     dest: /etc/default
#     owner: root
#     group: root
#     mode: '0644'
#   become: true
#   when: ansible_distribution == "Archlinux"

- name: Grub | Install grub
  tags:
    - grub
  ansible.builtin.package:
    name: grub
  become: true
  when: ansible_distribution == "Archlinux" and ansible_service_mgr == "grub"

- name: Grub | Change grub timeout to 0 second
  tags:
    - grub
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: .*GRUB_TIMEOUT=.*
    line: GRUB_TIMEOUT=0
    backrefs: true
  become: true
  when: ansible_service_mgr == "grub"
  register: update_grub

- name: Grub | Change grub timeout to hidden
  tags:
    - grub
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: .*GRUB_TIMEOUT_STYLE=.*
    line: GRUB_TIMEOUT_STYLE=hidden
    backrefs: true
  become: true
  when: ansible_service_mgr == "grub"
  register: update_grub2

- name: Grub | Speed up linux systems for workstations disabling mitigations - https://christitus.com/speedup-linux/
  tags:
    - grub
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: .*GRUB_CMDLINE_LINUX=.*
    line: GRUB_CMDLINE_LINUX="mitigations=off"
    backrefs: true
  become: true
  when: ansible_memtotal_mb > 16000 and ansible_service_mgr == "grub"
  register: update_grub3

- name: Grub | Speed up linux systems for workstations disabling mitigations and enable zswap compression - https://christitus.com/speedup-linux/
  tags:
    - grub
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: .*GRUB_CMDLINE_LINUX=.*
    line: GRUB_CMDLINE_LINUX="zswap.enabled=1 mitigations=off"
    backrefs: true
  become: true
  when: ansible_memtotal_mb <= 16000 and ansible_service_mgr == "grub"
  register: update_grub4

- name: Grub | Set grub to keep the latest kernel that were started (LTS or Bleeding edge)
  tags:
    - grub
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: .*GRUB_DEFAULT=.*
    line: GRUB_DEFAULT=saved
    backrefs: true
  become: true
  when: ansible_service_mgr == "grub"
  register: update_grub5

- name: Grub | Set grub to keep the latest kernel that were started (LTS or Bleeding edge)
  tags:
    - grub
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: .*GRUB_SAVEDEFAULT=.*
    line: GRUB_SAVEDEFAULT=true
    backrefs: true
  become: true
  when: ansible_service_mgr == "grub"
  register: update_grub6

- name: Grub | Copy file update-grub
  tags:
    - grub
  ansible.builtin.copy:
    src: update-grub
    dest: /usr/bin
    owner: root
    group: root
    mode: "0755"
  become: true
  when: update_grub is changed or update_grub2 is changed or update_grub3 is changed or update_grub4 is changed or update_grub5 is changed or update_grub6 is changed
    and ansible_service_mgr == "grub"
