---
- name: Check if grub is installed
  tags:
    - grub
  ansible.builtin.stat:
    path: /boot/grub
  register: grub_dir

- name: Grub | Install grub
  tags:
    - grub
  ansible.builtin.package:
    name: grub
  become: true
  when: ansible_distribution == "Archlinux" and grub_dir.stat.exists

- name: Get root filesystem type
  tags:
    - grub
  sansible.builtin.set_fact:
    rootfstype: "{{ item.fstype }}"
  loop: "{{ ansible_mounts }}"
  when: item.mount == "/"

- name: Grub | Install grub-btrfs when rootfstype is btrfs
  tags:
    - grub
  ansible.builtin.package:
    name: grub-btrfs
  become: true
  when: grub_dir.stat.exists and rootfstype == "btrfs"

- name: Grub | Change grub timeout to 1 second
  tags:
    - grub
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: .*GRUB_TIMEOUT=.*
    line: GRUB_TIMEOUT=1
    backrefs: true
  become: true
  when: grub_dir.stat.exists
  register: update_grub

- name: Grub | Change grub timeout to menu
  tags:
    - grub
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: .*GRUB_TIMEOUT_STYLE=.*
    line: GRUB_TIMEOUT_STYLE=menu
    backrefs: true
  become: true
  when: grub_dir.stat.exists
  register: update_grub2

- name: Grub | Speed up linux systems for workstations disabling mitigations - https://christitus.com/speedup-linux/
  tags:
    - grub
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: .*GRUB_CMDLINE_LINUX=.*
    line: GRUB_CMDLINE_LINUX="mitigations=off"
    backrefs: true
  become: true
  when: ansible_memtotal_mb > 16000 and grub_dir.stat.exists
  register: update_grub3

- name: Grub | Speed up linux systems for workstations disabling mitigations and enable zswap compression - https://christitus.com/speedup-linux/
  tags:
    - grub
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: .*GRUB_CMDLINE_LINUX=.*
    line: GRUB_CMDLINE_LINUX="zswap.enabled=1 mitigations=off"
    backrefs: true
  become: true
  when: ansible_memtotal_mb <= 16000 and grub_dir.stat.exists
  register: update_grub4

- name: Grub | Set grub to keep the latest kernel that were started (LTS or Bleeding edge)
  tags:
    - grub
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: .*GRUB_DEFAULT=.*
    line: GRUB_DEFAULT=saved
    backrefs: true
  become: true
  when: grub_dir.stat.exists
  register: update_grub5

- name: Grub | Set grub to keep the latest kernel that were started (LTS or Bleeding edge)
  tags:
    - grub
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: .*GRUB_SAVEDEFAULT=.*
    line: GRUB_SAVEDEFAULT=true
    backrefs: true
  become: true
  when: grub_dir.stat.exists
  register: update_grub6

- name: Grub | Copy file update-grub
  tags:
    - grub
  ansible.builtin.copy:
    src: update-grub
    dest: /usr/bin
    owner: root
    group: root
    mode: "0755"
  become: true
  when: >
    update_grub is changed
    or update_grub2 is changed
    or update_grub3 is changed
    or update_grub4 is changed
    or update_grub5 is changed
    or update_grub6 is changed
    and grub_dir.stat.exists
