---
- name: Linux Scripts | Clone linux-scripts
  tags:
    - scripts
  ansible.builtin.git:
    version: main
    repo: git@github.com:andre-gonzalez/linux-scripts.git
    dest: "{{ lookup('env', 'HOME') }}/.scripts"
    key_file: "{{ lookup('env', 'HOME') }}/.ssh/personal_id_ed25519_2023-11"
    accept_hostkey: true
  ignore_errors: true

- name: Linux Scripts | Copy files to .scripts
  tags:
    - scripts
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: instapaper, dest: "{{ lookup('env', 'HOME') }}/.scripts/.env/", mode: "0600" }
    - { src: mac-address-proxmox-server, dest: "{{ lookup('env', 'HOME') }}/.scripts/.env/", mode: "0600" }
    - { src: ipinfo, dest: "{{ lookup('env', 'HOME') }}/.scripts/.env/", mode: "0600" }

- name: Add another .scripts to system-wide $PATH.
  tags:
    - scripts
  ansible.builtin.copy:
    dest: /etc/profile.d/scripts.sh
    content: 'PATH=$PATH:{{ scripts_path }}'
    mode: '0644'
  become: true
