---
- name: Packages | Set packages variables when distribution is Archlinux (if necessary)
  tags:
    - packages
  ansible.builtin.set_fact:
    xorg:
      - xorg-server
      - xorg-xinit
      - xorg-xsetroot
      - xorg-xrandr
      - xorg-setxkbmap
      - xorg-xinput # Used on configure-trackball script
    rfkill: util-linux-libs
    python_pip: python-pip
    base_devel: base-devel
    wpa_supplicant: wpa_supplicant
    liberation_font: ttf-liberation
    postgres: postgresql-libs
    fd: fd
    notify: libnotify
  when: ansible_distribution == "Archlinux"

- name: Packages | Set packages variable when distribution is Ubuntu (if necessary)
  tags:
    - packages
  ansible.builtin.set_fact:
    xorg:
      - xorg
      - libxrandr2
      - libxrandr-dev
      - xorg
      - xorg
      - xinput # Used on configure-trackball script
    rfkill: rfkill
    python_pip: pipenv
    base_devel: make
    wpa_supplicant: wpasupplicant
    liberation_font: fonts-liberation
    postgres: postgresql
    fd: fd-find
    notify: libnotify-bin
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Packages | Install packages and update cache
  tags:
    - packages
  ansible.builtin.package:
    name:
      - tmux
      - tmuxp
      - "{{ xorg[0] }}"
      - "{{ xorg[1] }}"
      - "{{ xorg[2] }}"
      - "{{ xorg[3] }}"
      - "{{ xorg[4] }}"
      - "{{ xorg[5] }}"
      - xbindkeys
      - arandr
      - numlockx
      - "{{ python_pip }}"
      - feh
      - unclutter
      - "{{ base_devel }}"
      - xclip
      - brightnessctl
      - "{{ wpa_supplicant }}"
      - ripgrep
      - "{{ fd }}"
      - fzf
      - lxsession # polkit agent to fill password when launching applications with my run launcher
      - flameshot
      - bat
      - dunst
      - qt5ct # To set theme for qt applications
      - "{{ rfkill }}"
      - csvkit
      - yamllint
      - ansible-lint
      - npm # Necessary to install gramarly language server in neovim play
      - qutebrowser
      - unzip
      - "{{ liberation_font }}"
      - "{{ postgres }}"
      - "{{ notify }}"
      - mpv # Terminal based video player
      - yt-dlp # Download youtube videos, necessary to play youtube videos on mpv
      - pre-commit # To use with git to ensure format and linting before commits
      - rclone # I use to backup my data to AWS S3
      - bc # Terminal calculator
    state: present
    update_cache: true
  become: true

- name: Packages | Install packages that i still have not set in ubuntu
  tags:
    - packages
  ansible.builtin.package:
    name:
      - pamixer # missing ubuntu
      - ttf-nerd-fonts-symbols-mono # missing ubuntu
      - ttf-nerd-fonts-symbols-common
      - ttf-nerd-fonts-symbols
      - ttf-linux-libertine # missing ubuntu
      - clipmenu # missing ubuntu
      - noto-fonts-emoji # missing ubuntu
      - bleachbit # Utility to free space on disk
      - aws-cli-v2
      - python-debugpy # Pythan debugger dependency for nvim-dap-python
      - spotify-launcher
      - trash-cli
      - nethogs
      - man-db # Manpages
      - tldr # More concise man pages
      - git
      - zoxide # easily jump between directories using z + directory name
      - wol # provide Wake-on-Lan functionality
      - redshift # Adapt brightness and color of the screen at night
      - inetutils # Hostname command necessary for fish prompt
      - ntfs-3g # To mount drives formatted as NTFS
      - newsboat # RSS feed reader
      - python-adblock # To enable adblocking on qutebrowser
      - libreoffice-still # Office application
      - noto-fonts # Google Fonts
      - noto-fonts-extra # Additional variants of google fonts
      - ncdu # Terminal disk space usage explorer utility
      - git-delta # Better delta for git
      - pkgstats # Send list of installed packages to arch developers
      - dash
      - xcompmgr # X11 Compositor
      - python-pipx
    state: present
    update_cache: true
  become: true
  when: ansible_distribution == "Archlinux"
  register: _set_defaults

- name: Packages | Refresh fonts
  tags:
    - packages
  ansible.builtin.command: fc-cache
  register: refresh_fonts
  changed_when: refresh_fonts.rc != 2


- name: Set feh as default image viewer
  tags:
    - packages
  ansible.builtin.command: xdg-mime default feh.desktop image/png ; xdg-mime default feh.desktop image/jpeg
  when: _set_defaults is changed

- name: Set LibreOffice as default for MS Office formats
  tags:
    - packages
  ansible.builtin.command: >
    xdg-mime default libreoffice-impress.desktop application/vnd.openxmlformats-officedocument.presentationml.presentation ;
    xdg-mime default libreoffice-writer.desktop application/vnd.openxmlformats-officedocument.wordprocessingml.document ;
    xdg-mime default libreoffice-calc.desktop application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
  when: _set_defaults is changed
