---
- name: Packages | Set packages variables when distribution is Archlinux (if necessary)
  tags:
    - packages
  ansible.builtin.set_fact:
    light_workstation_xorg:
      - xorg-server
      - xorg-xinit
      - xorg-xsetroot
      - xorg-xrandr
      - xorg-setxkbmap
      - xorg-xinput # Used on configure-trackball script
      - xorg-xwininfo # Necessary for profile-selector script
    light_workstation_rfkill: util-linux-libs
    light_workstation_python_pip: python-pip
    light_workstation_base_devel: base-devel
    light_workstation_wpa_supplicant: wpa_supplicant
    light_workstation_liberation_font: ttf-liberation
    light_workstation_postgres: postgresql-libs
    light_workstation_fd: fd
    light_workstation_notify: libnotify
  when: ansible_facts["distribution"] == "Archlinux"

- name: Packages | Set packages variable when distribution is Ubuntu (if necessary)
  tags:
    - packages
  ansible.builtin.set_fact:
    light_workstation_xorg:
      - xorg
      - libxrandr2
      - libxrandr-dev
      - xorg
      - xorg
      - xinput # Used on configure-trackball script
    light_workstation_rfkill: rfkill
    light_workstation_python_pip: pipenv
    light_workstation_base_devel: make
    light_workstation_wpa_supplicant: wpasupplicant
    light_workstation_liberation_font: fonts-liberation
    light_workstation_postgres: postgresql
    light_workstation_fd: fd-find
    light_workstation_notify: libnotify-bin
  when: ansible_facts["distribution"] in ["Ubuntu", "Debian"]

- name: Packages | Install packages and update cache
  tags:
    - packages
  ansible.builtin.package:
    name:
      - tmux
      - tmuxp
      - "{{ light_workstation_xorg[0] }}"
      - "{{ light_workstation_xorg[1] }}"
      - "{{ light_workstation_xorg[2] }}"
      - "{{ light_workstation_xorg[3] }}"
      - "{{ light_workstation_xorg[4] }}"
      - "{{ light_workstation_xorg[5] }}"
      - xbindkeys
      - arandr
      - numlockx
      - "{{ light_workstation_python_pip }}"
      - feh
      - unclutter
      - "{{ light_workstation_base_devel }}"
      - xclip
      - brightnessctl
      - "{{ light_workstation_wpa_supplicant }}"
      - ripgrep
      - "{{ light_workstation_fd }}"
      - fzf
      - lxsession # polkit agent to fill password when launching applications with my run launcher
      - flameshot
      - bat
      - bat-extras
      - dunst
      - qt5ct # To set theme for qt applications
      - "{{ light_workstation_rfkill }}"
      - yamllint
      - ansible-lint
      - qutebrowser
      - unzip
      - "{{ light_workstation_liberation_font }}"
      - "{{ light_workstation_postgres }}"
      - "{{ light_workstation_notify }}"
      - mpv # Terminal based video player
      - yt-dlp # Download youtube videos, necessary to play youtube videos on mpv
      - pre-commit # To use with git to ensure format and linting before commits
      - bc # Terminal calculator
      - shellcheck # Shell script static analysis tool
      - shfmt # Format shell programs
    state: present
    update_cache: true
  become: true

- name: Packages | Install packages that i still have not set in ubuntu
  tags:
    - packages
  ansible.builtin.package:
    name:
      - pamixer # missing ubuntu
      - ttf-nerd-fonts-symbols-mono # missing ubuntu
      - ttf-nerd-fonts-symbols-common
      - ttf-nerd-fonts-symbols
      - ttf-linux-libertine # missing ubuntu
      - clipmenu # missing ubuntu
      - noto-fonts-emoji # missing ubuntu
      - noto-fonts-cjk # Chinese, Japanese and Korean fonts
      - bleachbit # Utility to free space on disk
      - aws-cli-v2
      - python-debugpy # Pythan debugger dependency for nvim-dap-python
      - spotify-launcher
      - trash-cli
      - nethogs
      - man-db # Manpages
      - tldr # More concise man pages
      - git
      - zoxide # easily jump between directories using z + directory name
      - wol # provide Wake-on-Lan functionality
      - redshift # Adapt brightness and color of the screen at night
      - inetutils # Hostname command necessary for fish prompt
      - ntfs-3g # To mount drives formatted as NTFS
      - newsboat # RSS feed reader
      - python-adblock # To enable adblocking on qutebrowser
      - libreoffice-still # Office application
      - noto-fonts # Google Fonts
      - noto-fonts-extra # Additional variants of google fonts
      - ncdu # Terminal disk space usage explorer utility
      - git-delta # Better delta for git
      - pkgstats # Send list of installed packages to arch developers
      - dash
      - picom # X11 Compositor
      - python-pipx
      - 7zip
      - tree # Utility to see directories structure in tree view
      - nfs-utils # Necessary to mount nfs shares on the system
    state: present
    update_cache: true
  become: true
  when: ansible_facts["distribution"] == "Archlinux"
  register: light_workstation_set_defaults

- name: Packages | Refresh fonts
  tags:
    - packages
  ansible.builtin.command: fc-cache
  register: light_workstation_refresh_fonts
  changed_when: light_workstation_refresh_fonts.rc != 2


- name: Packages | Set feh as default image viewer
  tags:
    - packages
  ansible.builtin.command: xdg-mime default feh.desktop image/png ; xdg-mime default feh.desktop image/jpeg
  when: light_workstation_set_defaults is changed

- name: Packages | Set LibreOffice as default for MS Office formats
  tags:
    - packages
  ansible.builtin.command: >
    xdg-mime default libreoffice-impress.desktop application/vnd.openxmlformats-officedocument.presentationml.presentation ;
    xdg-mime default libreoffice-writer.desktop application/vnd.openxmlformats-officedocument.wordprocessingml.document ;
    xdg-mime default libreoffice-calc.desktop application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
  when: light_workstation_set_defaults is changed

- name: Packages | Update tldr
  tags:
    - packages
  ansible.builtin.command: tldr --update
  when: light_workstation_set_defaults is changed
