---
- name: Spotify | Install spotify-player
  tags:
    - spotify
  ansible.builtin.package:
    name:
      - spotify-player
  become: true
  when: ansible_distribution == "Archlinux"

- name: Spotify | Copy file spotify-player
  tags:
    - spotify
  ansible.builtin.copy:
    src: spotify-player.toml
    dest: "{{ lookup('env', 'HOME') }}/.config/app.toml"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: "0640"
