---
- name: Web Browser | Install chromium
  tags:
    - web_browser
  ansible.builtin.package:
    name: chromium
  become: true
  when: ansible_distribution == "Archlinux"

- name: Web Browser | Copy ufw web browsing rule file
  tags:
    - web_browser
  ansible.builtin.copy:
    src: webrowser-ufw
    dest: /etc/ufw/applications.d/ufw-webrowser
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Web Browser | Allow web browsing in ufw
  tags:
    - web_browser
  community.general.ufw:
    rule: allow
    name: webrowser
    direction: out
    state: enabled
  become: true

- name: Web Browser | Install widevine and ffmpeg
  tags:
    - web_browser
  kewlfft.aur.aur:
    name:
      - chromium-widevine
      - chromium-ffmpeg
    use: yay
    state: present
    update_cache: true
  when: ansible_distribution == "Archlinux"
  ignore_errors: true
