---
- name: Wifi | Install iwd
  tags:
    - wifi
  ansible.builtin.package:
    name:
      - iwd
    state: present
    update_cache: false
  become: true
  notify: restart_network

- name: Wifi | Copy wifi configuration files
  tags:
    - wifi
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: /var/lib/iwd
    owner: root
    group: root
    mode: "0600"
  loop:
    - { src: Lopes.psk }
    - { src: LNAM5.psk }
    - { src: QueWiFi2.psk }
    - { src: CasaRio_5G.psk }
    - { src: =51756520576966693f.psk }
    - { src: Davi.psk }
  become: true
