# .github/workflows/ansible-lint.yml
name: ansible-lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v24.7.0
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ansible-lint-report
          path: ansible-lint-report/
          retention-days: 30
