---
# .github/workflows/ansible-lint.yml
name: ansible-lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Create vault password file
        run: |
          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > .vault_key
          chmod 600 .vault_key
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v26.6.0
