---
# .github/workflows/ansible-lint.yml
name: ansible-lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v25.7.0
